import type { AppLanguage } from './i18n';

const de = {
  'account.profileTitle': 'Profil & Einstellungen',
  'account.description': 'Dein Konto, deine wirksamen Rollen und deine Einstellungen.',
  'account.signedInAs': 'Angemeldet als',
  'account.loading': 'Konto wird geladen …',
  'account.loadError': 'Dein Kontostatus konnte nicht geladen werden. Bitte versuche es erneut.',
  'account.guest': 'Du bist nicht angemeldet oder deine Sitzung ist abgelaufen.',
  'account.loginHelp': 'Melde dich an, um dein eigenes Profil und deine Rollen zu sehen.',
  'account.loginUnavailable':
    'Die Anmeldung ist in dieser Umgebung noch nicht eingerichtet. Die öffentliche Suche bleibt verfügbar.',
  'account.readOnly': 'Kontodaten und Rollen sind hier schreibgeschützt.',
  'account.details': 'Konto',
  'account.displayName': 'Anzeigename',
  'account.username': 'Benutzername',
  'account.email': 'E-Mail',
  'account.userId': 'Konto-ID',
  'account.missing': 'Nicht vom Anmeldedienst bereitgestellt',
  'account.rolesTitle': 'Rollen & Zugehörigkeit',
  'account.applicationRoles': 'Wirksame Anwendungsrollen',
  'account.role.customer': 'Kunde',
  'account.role.moderator': 'Moderator',
  'account.role.admin': 'Admin',
  'account.memberships': 'Deine Garage-Mitgliedschaften',
  'account.membership.owner': 'Inhaber',
  'account.membership.editor': 'Bearbeiter',
  'account.noMemberships': 'Keine aktiven Garage-Mitgliedschaften vorhanden.',
  'account.membershipHelp':
    'Anwendungsrollen und Garage-Mitgliedschaften sind getrennt. Diese Anzeige erteilt keine zusätzlichen Berechtigungen.',
  'account.garageId': 'Garage-ID',
  'account.settings': 'Einstellungen',
  'account.languageHelp':
    'Die Sprachwahl gilt für die aktuelle Navigation über die URL. Sie wird nicht kontoweit gespeichert oder mit anderen Geräten synchronisiert.',
} as const;

export const accountCopy: Readonly<Record<AppLanguage, Readonly<Record<keyof typeof de, string>>>> =
  {
    de,
    sq: {
      'account.profileTitle': 'Profili & cilësimet',
      'account.description': 'Llogaria jote, rolet aktive dhe cilësimet e tua.',
      'account.signedInAs': 'I identifikuar si',
      'account.loading': 'Llogaria po ngarkohet …',
      'account.loadError': 'Gjendja e llogarisë nuk mund të ngarkohej. Provo përsëri.',
      'account.guest': 'Nuk je i identifikuar ose sesioni yt ka skaduar.',
      'account.loginHelp': 'Identifikohu për të parë profilin dhe rolet e tua.',
      'account.loginUnavailable':
        'Identifikimi nuk është konfiguruar ende në këtë mjedis. Kërkimi publik mbetet i disponueshëm.',
      'account.readOnly': 'Të dhënat e llogarisë dhe rolet këtu vetëm mund të lexohen.',
      'account.details': 'Llogaria',
      'account.displayName': 'Emri i shfaqur',
      'account.username': 'Emri i përdoruesit',
      'account.email': 'E-mail',
      'account.userId': 'ID-ja e llogarisë',
      'account.missing': 'Nuk është dhënë nga shërbimi i identifikimit',
      'account.rolesTitle': 'Rolet & anëtarësimet',
      'account.applicationRoles': 'Rolet aktive në aplikacion',
      'account.role.customer': 'Klient',
      'account.role.moderator': 'Moderator',
      'account.role.admin': 'Administrator',
      'account.memberships': 'Anëtarësimet e tua në servise',
      'account.membership.owner': 'Pronar',
      'account.membership.editor': 'Redaktor',
      'account.noMemberships': 'Nuk ke anëtarësime aktive në servise.',
      'account.membershipHelp':
        'Rolet e aplikacionit dhe anëtarësimet në servise janë të ndara. Kjo pamje nuk jep leje shtesë.',
      'account.garageId': 'ID-ja e servisit',
      'account.settings': 'Cilësimet',
      'account.languageHelp':
        'Zgjedhja e gjuhës vlen për navigimin aktual përmes URL-së. Ajo nuk ruhet për gjithë llogarinë dhe nuk sinkronizohet me pajisje të tjera.',
    },
    en: {
      'account.profileTitle': 'Profile & settings',
      'account.description': 'Your account, effective roles and settings.',
      'account.signedInAs': 'Signed in as',
      'account.loading': 'Loading account …',
      'account.loadError': 'Your account status could not be loaded. Please try again.',
      'account.guest': 'You are not signed in or your session has expired.',
      'account.loginHelp': 'Sign in to see your own profile and roles.',
      'account.loginUnavailable':
        'Sign-in has not been configured in this environment. Public search is still available.',
      'account.readOnly': 'Account details and roles are read-only here.',
      'account.details': 'Account',
      'account.displayName': 'Display name',
      'account.username': 'Username',
      'account.email': 'Email',
      'account.userId': 'Account ID',
      'account.missing': 'Not provided by the sign-in service',
      'account.rolesTitle': 'Roles & membership',
      'account.applicationRoles': 'Effective application roles',
      'account.role.customer': 'Customer',
      'account.role.moderator': 'Moderator',
      'account.role.admin': 'Admin',
      'account.memberships': 'Your garage memberships',
      'account.membership.owner': 'Owner',
      'account.membership.editor': 'Editor',
      'account.noMemberships': 'You have no active garage memberships.',
      'account.membershipHelp':
        'Application roles and garage memberships are separate. This display does not grant additional permissions.',
      'account.garageId': 'Garage ID',
      'account.settings': 'Settings',
      'account.languageHelp':
        'Your language choice applies to the current navigation through the URL. It is not saved account-wide or synchronized across devices.',
    },
  };
