export const favoritesCopy = {
  de: {
    title: 'Favoriten',
    description: 'Deine gemerkten Werkstätten. An einem Ort.',
    eyebrow: 'DEINE WERKSTATT-AUSWAHL',
    intro:
      'Behalte interessante Betriebe im Blick und finde sie hier wieder – unabhängig von deiner letzten Suche.',
    private: 'Nur für dich sichtbar',
    list: 'Deine Merkliste',
    count: '{count} gespeicherte Werkstätten',
    note: 'Favoriten sind deine persönliche Auswahl – keine Buchung oder Kontaktaufnahme.',
    empty: 'Noch keine Favoriten',
    emptyHelp:
      'Entdecke passende Werkstätten und tippe auf das Herz. Deine Auswahl wird in deinem Konto gespeichert.',
    search: 'Werkstätten finden',
    profile: 'Profil ansehen',
    remove: 'Entfernen',
    removeLabel: '{name} aus Favoriten entfernen',
    removing: 'Wird entfernt …',
    removeError: 'Nicht entfernt. Bitte versuche es erneut.',
    loading: 'Deine Favoriten werden geladen …',
    loadError: 'Deine Favoriten konnten nicht geladen werden.',
    unavailable: 'Nicht mehr verfügbar',
    unavailableHelp:
      'Dieses Profil ist nicht mehr öffentlich verfügbar. Du kannst es aus deinen Favoriten entfernen.',
    profileError: 'Profil gerade nicht ladbar',
    profileErrorHelp:
      'Die Werkstattdaten konnten nicht abgerufen werden. Dein Favorit bleibt gespeichert.',
    noPhoto: 'Noch kein Profilbild',
    noReviews: 'Noch keine Bewertungen',
    rating: '{rating} von 5 · {count} Bewertungen',
    verifiedVisits: '{count} belegte Besuche',
    verified: 'Unternehmensdaten geprüft',
    notVerified: 'Unternehmensdaten nicht geprüft',
    more: 'Weitere Favoriten laden',
    progress: '{shown} von {total} angezeigt',
    login: 'Anmelden und Favoriten ansehen',
    loginHelp:
      'Melde dich an, um deine gespeicherten Werkstätten zu sehen. Die öffentliche Suche bleibt ohne Konto nutzbar.',
    session: 'Deine Sitzung ist beendet. Melde dich erneut an.',
    retry: 'Erneut versuchen',
    moreServices: '+{count} weitere Leistungen',
  },
  sq: {
    title: 'Të preferuarat',
    description: 'Serviset e tua të ruajtura. Në një vend.',
    eyebrow: 'ZGJEDHJA JOTE E SERVISEVE',
    intro: 'Mbaji pranë serviset që të interesojnë dhe gjeji këtu, pavarësisht kërkimit të fundit.',
    private: 'Të dukshme vetëm për ty',
    list: 'Lista jote',
    count: '{count} servise të ruajtura',
    note: 'Të preferuarat janë zgjedhja jote personale – jo rezervim apo kontakt automatik.',
    empty: 'Ende asnjë i preferuar',
    emptyHelp: 'Zbulo servise të përshtatshme dhe prek zemrën. Zgjedhja ruhet në llogarinë tënde.',
    search: 'Gjej servise',
    profile: 'Shiko profilin',
    remove: 'Hiq',
    removeLabel: 'Hiq {name} nga të preferuarat',
    removing: 'Duke hequr …',
    removeError: 'Nuk u hoq. Provo përsëri.',
    loading: 'Duke ngarkuar të preferuarat …',
    loadError: 'Të preferuarat nuk u ngarkuan.',
    unavailable: 'Nuk është më i disponueshëm',
    unavailableHelp: 'Ky profil nuk është më publik. Mund ta heqësh nga të preferuarat.',
    profileError: 'Profili nuk mund të ngarkohet tani',
    profileErrorHelp: 'Të dhënat e servisit nuk u ngarkuan. I preferuari mbetet i ruajtur.',
    noPhoto: 'Ende pa foto profili',
    noReviews: 'Ende pa vlerësime',
    rating: '{rating} nga 5 · {count} vlerësime',
    verifiedVisits: '{count} vizita të dëshmuara',
    verified: 'Të dhënat e biznesit të kontrolluara',
    notVerified: 'Të dhënat e biznesit të pakontrolluara',
    more: 'Ngarko më shumë të preferuara',
    progress: 'Shfaqen {shown} nga {total}',
    login: 'Hyr për të parë të preferuarat',
    loginHelp: 'Hyr për të parë serviset e ruajtura. Kërkimi publik mbetet i hapur pa llogari.',
    session: 'Seanca jote ka përfunduar. Hyr përsëri.',
    retry: 'Provo përsëri',
    moreServices: '+{count} shërbime të tjera',
  },
  en: {
    title: 'Favorites',
    description: 'Your saved garages. All in one place.',
    eyebrow: 'YOUR GARAGE SHORTLIST',
    intro: 'Keep interesting garages close and find them here, regardless of your last search.',
    private: 'Only visible to you',
    list: 'Your shortlist',
    count: '{count} saved garages',
    note: 'Favorites are your personal shortlist – not a booking or an automatic message.',
    empty: 'No favorites yet',
    emptyHelp:
      'Discover suitable garages and tap the heart. Your choices are saved in your account.',
    search: 'Find garages',
    profile: 'View profile',
    remove: 'Remove',
    removeLabel: 'Remove {name} from favorites',
    removing: 'Removing …',
    removeError: 'Not removed. Please try again.',
    loading: 'Loading your favorites …',
    loadError: 'Your favorites could not be loaded.',
    unavailable: 'No longer available',
    unavailableHelp:
      'This profile is no longer public. You can still remove it from your favorites.',
    profileError: 'Profile cannot be loaded right now',
    profileErrorHelp: 'The garage details could not be loaded. Your favorite is still saved.',
    noPhoto: 'No profile photo yet',
    noReviews: 'No reviews yet',
    rating: '{rating} out of 5 · {count} reviews',
    verifiedVisits: '{count} verified visits',
    verified: 'Company details checked',
    notVerified: 'Company details not checked',
    more: 'Load more favorites',
    progress: 'Showing {shown} of {total}',
    login: 'Sign in to view favorites',
    loginHelp:
      'Sign in to see your saved garages. Public search is still available without an account.',
    session: 'Your session has ended. Please sign in again.',
    retry: 'Try again',
    moreServices: '+{count} more services',
  },
} as const;
export type FavoritesCopyKey = keyof typeof favoritesCopy.de;
