const de = {
  forbidden:
    'Du hast keine Berechtigung für diese Änderung. Aktualisiere die Übersicht oder wende dich an den Support.',
  csrfError:
    'Die Sicherheitsprüfung ist fehlgeschlagen. Prüfe deine Anmeldung und versuche es erneut.',
  subtitle: 'Gespeicherte Anfragen ansehen, anpassen und wiederverwenden.',
  all: 'Alle Anfragen',
  active: 'Aktiv',
  inactive: 'Deaktiviert',
  sort: 'Neueste zuerst',
  filterLabel: 'Anfragen filtern',
  actions: 'Weitere Aktionen',
  edit: 'Bearbeiten',
  deactivate: 'Deaktivieren',
  reactivate: 'Reaktivieren',
  delete: 'Löschen',
  deleteTitle: 'Anfrage endgültig löschen?',
  deleteBody:
    'Die Anfrage, ihre Suchorte und zugehörigen Fahrzeugangaben werden gelöscht. Das lässt sich nicht rückgängig machen.',
  fileRetention:
    'Separat gespeicherte Dateien werden dadurch nicht gelöscht. Sie bleiben privat und unterliegen ihrer eigenen Aufbewahrung.',
  cancel: 'Abbrechen',
  save: 'Änderungen speichern',
  saving: 'Wird gespeichert …',
  editTitle: 'Anfrage bearbeiten',
  editHelp:
    'Änderungen gelten nur für diese gespeicherte Anfrage. Dein Entwurf für eine neue Anfrage bleibt unverändert.',
  discardTitle: 'Änderungen verwerfen?',
  discardBody:
    'Deine Änderungen sind noch nicht gespeichert. Möchtest du den Editor trotzdem schließen?',
  discard: 'Änderungen verwerfen',
  keepEditing: 'Weiter bearbeiten',
  conflict:
    'Diese Anfrage wurde inzwischen geändert. Deine Eingaben wurden nicht gespeichert. Schließe den Editor und lade die aktuelle Version, bevor du es erneut versuchst.',
  writeError:
    'Die Änderung wurde nicht bestätigt. Prüfe die Übersicht oder versuche es erneut. Nicht gespeicherte Eingaben bleiben im geöffneten Editor erhalten.',
  updated: 'Änderungen gespeichert.',
  deactivated: 'Anfrage deaktiviert. Deine Angaben bleiben gespeichert.',
  reactivated: 'Anfrage wieder aktiviert.',
  deleted: 'Anfrage gelöscht.',
  updatedOn: 'Geändert am',
  noMatches: 'Keine Anfragen in dieser Ansicht',
  noMatchesHelp: 'Wechsle zu „Alle Anfragen“ oder erstelle eine neue Anfrage.',
  privacyTitle: 'Nur für dich gespeichert',
  privacyBody: 'Deine Anfragen sind privat. Es wird nichts automatisch an eine Werkstatt gesendet.',
  nextTitle: 'Du entscheidest, wie es weitergeht',
  nextBody:
    'Finde passende Werkstätten und wähle selbst, wen du kontaktierst. Eine gespeicherte Anfrage ist noch kein Auftrag.',
  statusHelp:
    'Deaktivierte Anfragen bleiben erhalten. Du kannst sie jederzeit reaktivieren und für eine neue Suche verwenden.',
  validation: 'Bitte prüfe Leistung, Orte, Fahrzeugangaben und Datumsreihenfolge.',
  attachmentsKept:
    'Vorhandene Anhänge bleiben unverändert. Neue Dateien werden hier nicht hochgeladen.',
  closeEditor: 'Editor schließen',
  privateLabel: 'Privat',
  viewShort: 'Details',
  findShort: 'Werkstätten finden',
  emptyIconLabel: 'Gespeicherte Anfragen',
  title: 'Meine Anfragen',
  description:
    'Deine privat gespeicherten Suchanfragen. Sie sind keine gesendeten Nachrichten, Angebote, Termine oder Aufträge.',
  savedOn: 'Gespeichert am',
  emptyTitle: 'Noch keine gespeicherten Anfragen',
  empty:
    'Hier erscheinen nur Anfragen, die du in diesem Konto gespeichert hast. Ein lokaler Browserentwurf gehört nicht dazu.',
  view: 'Anfrage ansehen',
  close: 'Details schließen',
  find: 'Passende Werkstätten finden',
  more: 'Weitere Anfragen laden',
  loadError: 'Deine Anfragen konnten nicht geladen werden. Bitte versuche es erneut.',
  missing: 'Diese Anfrage ist nicht mehr verfügbar. Aktualisiere die Übersicht.',
  refresh: 'Übersicht aktualisieren',
  detailError: 'Die gespeicherten Angaben konnten nicht geladen werden.',
  login:
    'Melde dich an, um deine gespeicherten Anfragen zu sehen. Danach kehrst du hierher zurück.',
  expired:
    'Deine Sitzung ist abgelaufen oder wurde beendet. Melde dich erneut an, um deine Anfragen zu sehen.',
  allKosovo: 'Ganz Kosovo',
  areas: 'Suchorte',
  savedDetails: 'Gespeicherte Angaben',
  original: 'Deine Angaben werden unverändert in ihrer ursprünglichen Sprache angezeigt.',
  attachments: 'Gespeicherte private Anhänge',
  noAttachments: 'Keine Anhänge gespeichert',
  attachmentsHelp: 'Es werden keine privaten Dateien öffentlich verlinkt.',
  searchHelp:
    'Die Suche übernimmt nur Leistung, Orte und Radien. Dein Browserentwurf bleibt unverändert.',
};
export type InquiriesCopyKey = keyof typeof de;
export const inquiriesCopy: Readonly<
  Record<'de' | 'sq' | 'en', Readonly<Record<InquiriesCopyKey, string>>>
> = {
  de,
  sq: {
    forbidden: 'Nuk ke leje për këtë ndryshim. Rifresko përmbledhjen ose kontakto mbështetjen.',
    csrfError: 'Kontrolli i sigurisë dështoi. Kontrollo identifikimin dhe provo përsëri.',
    subtitle: 'Shiko, ndrysho dhe ripërdor kërkesat e ruajtura.',
    all: 'Të gjitha',
    active: 'Aktive',
    inactive: 'Çaktivizuar',
    sort: 'Më të rejat së pari',
    filterLabel: 'Filtro kërkesat',
    actions: 'Veprime të tjera',
    edit: 'Ndrysho',
    deactivate: 'Çaktivizo',
    reactivate: 'Riaktivizo',
    delete: 'Fshi',
    deleteTitle: 'Ta fshish përfundimisht kërkesën?',
    deleteBody:
      'Kërkesa, vendet e kërkimit dhe të dhënat përkatëse të automjetit do të fshihen. Ky veprim nuk mund të zhbëhet.',
    fileRetention:
      'Skedarët e ruajtur veçmas nuk fshihen nga ky veprim. Ata mbeten privatë dhe i nënshtrohen politikës së tyre të ruajtjes.',
    cancel: 'Anulo',
    save: 'Ruaj ndryshimet',
    saving: 'Duke ruajtur …',
    editTitle: 'Ndrysho kërkesën',
    editHelp:
      'Ndryshimet vlejnë vetëm për këtë kërkesë të ruajtur. Drafti yt për një kërkesë të re mbetet i pandryshuar.',
    discardTitle: 'Të hidhen poshtë ndryshimet?',
    discardBody: 'Ndryshimet nuk janë ruajtur ende. Dëshiron ta mbyllësh redaktorin?',
    discard: 'Hidhi poshtë',
    keepEditing: 'Vazhdo ndryshimin',
    conflict:
      'Kjo kërkesë është ndryshuar ndërkohë. Ndryshimet e tua nuk u ruajtën. Mbyll redaktorin dhe ngarko versionin aktual para se të provosh përsëri.',
    writeError:
      'Ndryshimi nuk u konfirmua. Kontrollo përmbledhjen ose provo përsëri. Të dhënat e paruajtura mbeten në redaktorin e hapur.',
    updated: 'Ndryshimet u ruajtën.',
    deactivated: 'Kërkesa u çaktivizua. Të dhënat mbeten të ruajtura.',
    reactivated: 'Kërkesa u riaktivizua.',
    deleted: 'Kërkesa u fshi.',
    updatedOn: 'Ndryshuar më',
    noMatches: 'Nuk ka kërkesa në këtë pamje',
    noMatchesHelp: 'Kalo te të gjitha kërkesat ose krijo një të re.',
    privacyTitle: 'Ruajtur vetëm për ty',
    privacyBody: 'Kërkesat e tua janë private. Asgjë nuk u dërgohet automatikisht serviseve.',
    nextTitle: 'Ti vendos hapin e radhës',
    nextBody:
      'Gjej servise të përshtatshme dhe zgjidh vetë kë të kontaktosh. Një kërkesë e ruajtur nuk është porosi.',
    statusHelp:
      'Kërkesat e çaktivizuara mbeten të ruajtura. Mund t’i riaktivizosh dhe t’i përdorësh sërish për kërkim.',
    validation: 'Kontrollo shërbimin, vendet, të dhënat e automjetit dhe renditjen e datave.',
    attachmentsKept:
      'Bashkëngjitjet ekzistuese mbeten të pandryshuara. Këtu nuk ngarkohen skedarë të rinj.',
    closeEditor: 'Mbyll redaktorin',
    privateLabel: 'Private',
    viewShort: 'Detaje',
    findShort: 'Gjej servise',
    emptyIconLabel: 'Kërkesat e ruajtura',
    title: 'Kërkesat e mia',
    description:
      'Kërkesat e tua të kërkimit, të ruajtura privatisht. Ato nuk janë mesazhe të dërguara, oferta, termine apo porosi.',
    savedOn: 'Ruajtur më',
    emptyTitle: 'Ende nuk ka kërkesa të ruajtura',
    empty:
      'Këtu shfaqen vetëm kërkesat që i ke ruajtur në këtë llogari. Një draft lokal në shfletues nuk përfshihet.',
    view: 'Shiko kërkesën',
    close: 'Mbyll detajet',
    find: 'Gjej servise të përshtatshme',
    more: 'Ngarko kërkesa të tjera',
    loadError: 'Kërkesat e tua nuk mund të ngarkoheshin. Provo përsëri.',
    missing: 'Kjo kërkesë nuk është më e disponueshme. Rifresko përmbledhjen.',
    refresh: 'Rifresko përmbledhjen',
    detailError: 'Të dhënat e ruajtura nuk mund të ngarkoheshin.',
    login: 'Hyr në llogari për të parë kërkesat e ruajtura. Pastaj do të kthehesh këtu.',
    expired: 'Sesioni yt ka skaduar ose është përfunduar. Hyr përsëri për të parë kërkesat e tua.',
    allKosovo: 'Gjithë Kosova',
    areas: 'Vendet e kërkimit',
    savedDetails: 'Të dhënat e ruajtura',
    original: 'Të dhënat e tua shfaqen të pandryshuara në gjuhën origjinale.',
    attachments: 'Bashkëngjitjet private të ruajtura',
    noAttachments: 'Nuk ka bashkëngjitje të ruajtura',
    attachmentsHelp: 'Skedarët privatë nuk lidhen publikisht.',
    searchHelp:
      'Kërkimi merr vetëm shërbimin, vendet dhe rrezet. Drafti yt në shfletues mbetet i pandryshuar.',
  },
  en: {
    forbidden:
      'You do not have permission to make this change. Refresh the overview or contact support.',
    csrfError: 'The security check failed. Check your sign-in and try again.',
    subtitle: 'View, update and reuse your saved inquiries.',
    all: 'All inquiries',
    active: 'Active',
    inactive: 'Deactivated',
    sort: 'Newest first',
    filterLabel: 'Filter inquiries',
    actions: 'More actions',
    edit: 'Edit',
    deactivate: 'Deactivate',
    reactivate: 'Reactivate',
    delete: 'Delete',
    deleteTitle: 'Permanently delete this inquiry?',
    deleteBody:
      'The inquiry, its search locations and associated vehicle details will be deleted. This cannot be undone.',
    fileRetention:
      'Separately stored files are not deleted by this action. They remain private and follow their own retention policy.',
    cancel: 'Cancel',
    save: 'Save changes',
    saving: 'Saving …',
    editTitle: 'Edit inquiry',
    editHelp:
      'Changes apply only to this saved inquiry. Your draft for a new inquiry stays unchanged.',
    discardTitle: 'Discard changes?',
    discardBody: 'Your changes have not been saved. Do you still want to close the editor?',
    discard: 'Discard changes',
    keepEditing: 'Keep editing',
    conflict:
      'This inquiry has changed since you opened it. Your changes were not saved. Close the editor and load the current version before trying again.',
    writeError:
      'The change was not confirmed. Check the overview or try again. Unsaved input remains in the open editor.',
    updated: 'Changes saved.',
    deactivated: 'Inquiry deactivated. Your information is still saved.',
    reactivated: 'Inquiry reactivated.',
    deleted: 'Inquiry deleted.',
    updatedOn: 'Updated on',
    noMatches: 'No inquiries in this view',
    noMatchesHelp: 'Switch to all inquiries or create a new one.',
    privacyTitle: 'Saved just for you',
    privacyBody: 'Your inquiries are private. Nothing is automatically sent to a garage.',
    nextTitle: 'You choose the next step',
    nextBody:
      'Find matching garages and choose who to contact yourself. A saved inquiry is not an order.',
    statusHelp:
      'Deactivated inquiries are kept. Reactivate them at any time to use them for another search.',
    validation: 'Check the service, locations, vehicle details and date order.',
    attachmentsKept: 'Existing attachments stay unchanged. New files are not uploaded here.',
    closeEditor: 'Close editor',
    privateLabel: 'Private',
    viewShort: 'Details',
    findShort: 'Find garages',
    emptyIconLabel: 'Saved inquiries',
    title: 'My inquiries',
    description:
      'Your privately saved search inquiries. These are not sent messages, quotes, appointments or orders.',
    savedOn: 'Saved on',
    emptyTitle: 'No saved inquiries yet',
    empty:
      'Only inquiries you saved to this account appear here. A local browser draft is not included.',
    view: 'View inquiry',
    close: 'Close details',
    find: 'Find matching garages',
    more: 'Load more inquiries',
    loadError: 'Your inquiries could not be loaded. Please try again.',
    missing: 'This inquiry is no longer available. Refresh the overview.',
    refresh: 'Refresh overview',
    detailError: 'The saved details could not be loaded.',
    login: 'Sign in to view your saved inquiries. You will return here afterwards.',
    expired: 'Your session has expired or ended. Sign in again to view your inquiries.',
    allKosovo: 'All of Kosovo',
    areas: 'Search locations',
    savedDetails: 'Saved details',
    original: 'Your information is shown unchanged in its original language.',
    attachments: 'Saved private attachments',
    noAttachments: 'No saved attachments',
    attachmentsHelp: 'Private files are not linked publicly.',
    searchHelp:
      'Search uses only the service, places and radii. Your browser draft stays unchanged.',
  },
};
