import type { AppLanguage } from './i18n';

export const landingCopy: Readonly<Record<AppLanguage, Readonly<Record<string, string>>>> = {
  de: {
    'account.title': 'Mein Konto',
    'account.notifications': 'Benachrichtigungen',
    'account.notificationsUnavailable': 'Benachrichtigungen sind noch nicht verfügbar.',
    'account.logout': 'Abmelden',
    'account.logoutError': 'Abmelden ist fehlgeschlagen. Bitte erneut versuchen.',

    'landing.skip': 'Zum Inhalt',
    'landing.benefits': 'Deine Vorteile',
    'nav.main': 'Hauptnavigation',
    'nav.mobile': 'Mobile Navigation',
    'nav.search': 'Werkstätten finden',
    'nav.newRequest': 'Neue Anfrage',
    'nav.myRequests': 'Meine Anfragen',
    'nav.favorites': 'Favoriten',
    'nav.privateUnavailable': 'Diese private Ansicht ist noch nicht verfügbar.',
    'nav.how': 'So funktioniert’s',
    'nav.workshops': 'Für Werkstätten',
    'nav.about': 'Über uns',
    'nav.login': 'Login',
    'nav.register': 'Registrieren',
    'nav.open': 'Menü öffnen',
    'nav.close': 'Menü schließen',
    'landing.pageTitle': 'Deine Werkstatt in Kosovo. Schon vor der Reise.',
    'landing.titleOne': 'Deine Werkstatt',
    'landing.titleTwo': 'in Kosovo.',
    'landing.titleAccent': 'Schon vor der Reise.',
    'landing.intro':
      'Finde passende Werkstätten, vergleiche Erfahrungen und plane deine Reparatur entspannt. Die Entscheidung bleibt bei dir.',
    'landing.checked': 'Unternehmensdaten geprüft',
    'landing.experiences': 'Nachvollziehbare Kundenerfahrungen',
    'landing.vehicle': 'Passend zu deinem Fahrzeug',
    'landing.request': 'Jetzt Anfrage erstellen',
    'landing.free': 'Kostenlos & unverbindlich',
    'landing.direct': 'Lieber direkt eine Werkstatt suchen',
    'landing.quote': 'Gjithmonë një hap më afër shtëpisë.',
    'landing.choiceLabel': 'Du entscheidest.',
    'landing.choiceTitle': 'Deine Werkstatt. Dein Kontakt.',
    'landing.choiceBody': 'Persönlich auswählen und direkt abstimmen.',
    'landing.timeTitle': 'Mehr Zeit für das Wesentliche',
    'landing.timeBody': 'Einfach suchen, in Ruhe planen.',
    'landing.choiceBenefit': 'Eine Auswahl, die zu dir passt',
    'landing.choiceBenefitBody': 'Mit nachvollziehbaren Erfahrungen.',
    'landing.trustTitle': 'Vertrauen beginnt mit Klarheit',
    'landing.trustBody': 'Unternehmensdaten und Erfahrungen im Blick.',
    'landing.searchEyebrow': 'DEIN WEG ZUR PASSENDEN WERKSTATT',
    'landing.searchTitle': 'Was braucht dein Fahrzeug?',
    'landing.searchBody':
      'Wähle die gewünschte Leistung und einen Ort in Kosovo. Vergleiche passende Betriebe und entscheide selbst, wen du kontaktierst.',
    'landing.noAccount': 'Suchen und Kontakt auswählen – ohne Konto.',
    'landing.invalidPlace': 'Bitte wähle einen Ort aus der Liste.',
    'landing.howTitle': 'In drei Schritten zur passenden Werkstatt',
    'landing.stepOneTitle': 'Sag uns, was du suchst',
    'landing.stepOneBody':
      'Wähle Leistung und Ort. Für mehr Details kannst du eine persönliche Reparaturanfrage vorbereiten.',
    'landing.stepTwoTitle': 'Vergleiche in Ruhe',
    'landing.stepTwoBody':
      'Sieh dir Leistungen, Unternehmensangaben und veröffentlichte Erfahrungen an.',
    'landing.stepThreeTitle': 'Nimm selbst Kontakt auf',
    'landing.stepThreeBody':
      'Wähle einen Betrieb und stimme Reparatur, Preis und Termin direkt ab.',
    'landing.aboutTitle': 'Ein gutes Gefühl auf dem Weg nach Hause.',
    'landing.aboutBody':
      'AutoKosova hilft dir, schon vor deiner Reise eine passende Werkstatt in Kosovo zu finden. Mit übersichtlichen Informationen und dem Kontakt, den du selbst auswählst.',
    'landing.verification':
      'Das Kennzeichen „Unternehmensdaten geprüft“ zeigt eine Prüfung der Unternehmensangaben an. Es ist keine Garantie für Reparaturqualität oder freie Termine. Besuchsnachweise bei Bewertungen werden separat geprüft.',
    'landing.footer': 'Dein Fahrzeug. Deine Entscheidung.',
  },
  sq: {
    'account.title': 'Llogaria ime',
    'account.notifications': 'Njoftimet',
    'account.notificationsUnavailable': 'Njoftimet nuk janë ende të disponueshme.',
    'account.logout': 'Dil',
    'account.logoutError': 'Dalja dështoi. Provo përsëri.',

    'landing.skip': 'Te përmbajtja',
    'landing.benefits': 'Përparësitë e tua',
    'nav.main': 'Navigimi kryesor',
    'nav.mobile': 'Navigimi në telefon',
    'nav.search': 'Gjej servise',
    'nav.newRequest': 'Kërkesë e re',
    'nav.myRequests': 'Kërkesat e mia',
    'nav.favorites': 'Të preferuarat',
    'nav.privateUnavailable': 'Kjo pamje private nuk është ende e disponueshme.',
    'nav.how': 'Si funksionon',
    'nav.workshops': 'Për serviset',
    'nav.about': 'Rreth nesh',
    'nav.login': 'Hyr',
    'nav.register': 'Regjistrohu',
    'nav.open': 'Hap menynë',
    'nav.close': 'Mbyll menynë',
    'landing.pageTitle': 'Servisi yt në Kosovë. Para se të nisesh.',
    'landing.titleOne': 'Servisi yt',
    'landing.titleTwo': 'në Kosovë.',
    'landing.titleAccent': 'Para se të nisesh.',
    'landing.intro':
      'Gjej servise të përshtatshme, krahaso përvojat dhe planifiko riparimin me qetësi. Vendimi mbetet i yti.',
    'landing.checked': 'Të dhënat e biznesit të kontrolluara',
    'landing.experiences': 'Përvoja të dokumentuara të klientëve',
    'landing.vehicle': 'I përshtatshëm për automjetin tënd',
    'landing.request': 'Krijo kërkesën tani',
    'landing.free': 'Falas dhe pa detyrim',
    'landing.direct': 'Kërko drejtpërdrejt një servis',
    'landing.quote': 'Gjithmonë një hap më afër shtëpisë.',
    'landing.choiceLabel': 'Ti vendos.',
    'landing.choiceTitle': 'Servisi yt. Kontakti yt.',
    'landing.choiceBody': 'Zgjidh vetë dhe bisedo drejtpërdrejt.',
    'landing.timeTitle': 'Më shumë kohë për të rëndësishmet',
    'landing.timeBody': 'Kërko lehtë, planifiko me qetësi.',
    'landing.choiceBenefit': 'Zgjedhja që të përshtatet',
    'landing.choiceBenefitBody': 'Me përvoja të dokumentuara.',
    'landing.trustTitle': 'Besimi fillon me qartësi',
    'landing.trustBody': 'Të dhënat e biznesit dhe përvojat në një vend.',
    'landing.searchEyebrow': 'RRUGA JOTE DREJT SERVISIT TË DUHUR',
    'landing.searchTitle': 'Çfarë i duhet automjetit tënd?',
    'landing.searchBody':
      'Zgjidh shërbimin dhe një vend në Kosovë. Krahaso serviset e përshtatshme dhe vendos vetë kë të kontaktosh.',
    'landing.noAccount': 'Kërko dhe zgjidh kontaktin – pa llogari.',
    'landing.invalidPlace': 'Zgjidh një vend nga lista.',
    'landing.howTitle': 'Në tre hapa drejt servisit të duhur',
    'landing.stepOneTitle': 'Na trego çfarë kërkon',
    'landing.stepOneBody':
      'Zgjidh shërbimin dhe vendin. Për më shumë hollësi, përgatit një kërkesë personale për riparim.',
    'landing.stepTwoTitle': 'Krahaso me qetësi',
    'landing.stepTwoBody': 'Shiko shërbimet, të dhënat e biznesit dhe përvojat e publikuara.',
    'landing.stepThreeTitle': 'Kontakto vetë',
    'landing.stepThreeBody':
      'Zgjidh një servis dhe bisedo drejtpërdrejt për riparimin, çmimin dhe datën.',
    'landing.aboutTitle': 'Një ndjenjë e mirë në rrugën për në shtëpi.',
    'landing.aboutBody':
      'AutoKosova të ndihmon të gjesh një servis të përshtatshëm në Kosovë para udhëtimit. Me informacion të qartë dhe kontaktin që e zgjedh vetë.',
    'landing.verification':
      'Shenja “Të dhënat e biznesit të kontrolluara” tregon kontrollin e të dhënave të biznesit. Nuk garanton cilësinë e riparimit ose termine të lira. Dëshmitë e vizitave për vlerësimet kontrollohen veçmas.',
    'landing.footer': 'Automjeti yt. Vendimi yt.',
  },
  en: {
    'account.title': 'My account',
    'account.notifications': 'Notifications',
    'account.notificationsUnavailable': 'Notifications are not available yet.',
    'account.logout': 'Sign out',
    'account.logoutError': 'Sign out failed. Please try again.',

    'landing.skip': 'Skip to content',
    'landing.benefits': 'Your benefits',
    'nav.main': 'Main navigation',
    'nav.mobile': 'Mobile navigation',
    'nav.search': 'Find garages',
    'nav.newRequest': 'New request',
    'nav.myRequests': 'My requests',
    'nav.favorites': 'Favorites',
    'nav.privateUnavailable': 'This private view is not available yet.',
    'nav.how': 'How it works',
    'nav.workshops': 'For garages',
    'nav.about': 'About us',
    'nav.login': 'Log in',
    'nav.register': 'Register',
    'nav.open': 'Open menu',
    'nav.close': 'Close menu',
    'landing.pageTitle': 'Your garage in Kosovo. Before you travel.',
    'landing.titleOne': 'Your garage',
    'landing.titleTwo': 'in Kosovo.',
    'landing.titleAccent': 'Before you travel.',
    'landing.intro':
      'Find suitable garages, compare experiences and plan your repair at your own pace. The choice stays yours.',
    'landing.checked': 'Company data checked',
    'landing.experiences': 'Documented customer experiences',
    'landing.vehicle': 'Suitable for your vehicle',
    'landing.request': 'Create a request',
    'landing.free': 'Free & no obligation',
    'landing.direct': 'Go straight to the garage search',
    'landing.quote': 'Gjithmonë një hap më afër shtëpisë.',
    'landing.choiceLabel': 'You decide.',
    'landing.choiceTitle': 'Your garage. Your contact.',
    'landing.choiceBody': 'Choose personally and discuss directly.',
    'landing.timeTitle': 'More time for what matters',
    'landing.timeBody': 'Search easily, plan at your own pace.',
    'landing.choiceBenefit': 'A choice that suits you',
    'landing.choiceBenefitBody': 'With documented experiences.',
    'landing.trustTitle': 'Trust starts with clarity',
    'landing.trustBody': 'Company information and experiences at a glance.',
    'landing.searchEyebrow': 'YOUR WAY TO THE RIGHT GARAGE',
    'landing.searchTitle': 'What does your vehicle need?',
    'landing.searchBody':
      'Choose a service and a place in Kosovo. Compare suitable garages and decide whom to contact.',
    'landing.noAccount': 'Search and choose a contact – without an account.',
    'landing.invalidPlace': 'Please choose a place from the list.',
    'landing.howTitle': 'Three steps to the right garage',
    'landing.stepOneTitle': 'Tell us what you need',
    'landing.stepOneBody':
      'Choose a service and a location. For more detail, prepare a personal repair request.',
    'landing.stepTwoTitle': 'Compare at your own pace',
    'landing.stepTwoBody': 'Explore services, company information and published experiences.',
    'landing.stepThreeTitle': 'Make contact yourself',
    'landing.stepThreeBody': 'Choose a garage and agree the repair, price and timing directly.',
    'landing.aboutTitle': 'A good feeling on the way home.',
    'landing.aboutBody':
      'AutoKosova helps you find a suitable garage in Kosovo before you travel. With clear information and a contact you choose yourself.',
    'landing.verification':
      'The “Company data checked” label indicates a check of company information. It does not guarantee repair quality or available appointments. Visit evidence for reviews is checked separately.',
    'landing.footer': 'Your vehicle. Your decision.',
  },
};
