import type { AppLanguage } from './i18n';

export const landingCopy: Readonly<Record<AppLanguage, Readonly<Record<string, string>>>> = {
  de: {
    'account.title': 'Mein Konto',
    'account.notifications': 'Benachrichtigungen',
    'account.notificationsUnavailable': 'Benachrichtigungen sind noch nicht verfügbar.',
    'account.logout': 'Abmelden',
    'account.logoutError': 'Abmelden ist fehlgeschlagen. Bitte erneut versuchen.',

    'landing.skip': 'Zum Inhalt',
    'landing.benefits': 'Deine Vorteile',
    'nav.main': 'Hauptnavigation',
    'nav.mobile': 'Mobile Navigation',
    'nav.search': 'Werkstätten finden',
    'nav.newRequest': 'Neue Anfrage',
    'nav.myRequests': 'Meine Anfragen',
    'nav.favorites': 'Favoriten',
    'nav.privateUnavailable': 'Diese private Ansicht ist noch nicht verfügbar.',
    'nav.garages': 'Für Werkstätten',
    'nav.login': 'Login',
    'nav.register': 'Registrieren',
    'nav.open': 'Menü öffnen',
    'nav.close': 'Menü schließen',
    'landing.pageTitle': 'Deine Werkstatt in Kosovo. Schon vor der Reise.',
    'landing.titleOne': 'Deine Werkstatt',
    'landing.titleTwo': 'in Kosovo.',
    'landing.titleAccent': 'Schon vor der Reise.',
    'landing.intro':
      'Finde passende Werkstätten, vergleiche Erfahrungen und plane deine Reparatur entspannt. Die Entscheidung bleibt bei dir.',
    'landing.checked': 'Unternehmensdaten geprüft',
    'landing.experiences': 'Nachvollziehbare Kundenerfahrungen',
    'landing.vehicle': 'Passend zu deinem Fahrzeug',
    'landing.request': 'Jetzt Anfrage erstellen',
    'landing.free': 'Kostenlos & unverbindlich',
    'landing.direct': 'Lieber direkt eine Werkstatt suchen',
    'landing.choiceLabel': 'Du entscheidest.',
    'landing.choiceTitle': 'Deine Werkstatt. Dein Kontakt.',
    'landing.choiceBody': 'Persönlich auswählen und direkt abstimmen.',
    'landing.timeTitle': 'Mehr Zeit für das Wesentliche',
    'landing.timeBody': 'Einfach suchen, in Ruhe planen.',
    'landing.choiceBenefit': 'Eine Auswahl, die zu dir passt',
    'landing.choiceBenefitBody': 'Mit nachvollziehbaren Erfahrungen.',
    'landing.trustTitle': 'Vertrauen beginnt mit Klarheit',
    'landing.trustBody': 'Unternehmensdaten und Erfahrungen im Blick.',
    'landing.searchEyebrow': 'DEIN WEG ZUR PASSENDEN WERKSTATT',
    'landing.searchTitle': 'Was braucht dein Fahrzeug?',
    'landing.searchBody':
      'Wähle die gewünschte Leistung und einen Ort in Kosovo. Vergleiche passende Betriebe und entscheide selbst, wen du kontaktierst.',
    'landing.noAccount': 'Suchen und Kontakt auswählen – ohne Konto.',
    'landing.invalidPlace': 'Bitte wähle einen Ort aus der Liste.',
    'landing.footer': 'Dein Fahrzeug. Deine Entscheidung.',
  },
  sq: {
    'account.title': 'Llogaria ime',
    'account.notifications': 'Njoftimet',
    'account.notificationsUnavailable': 'Njoftimet nuk janë ende të disponueshme.',
    'account.logout': 'Dil',
    'account.logoutError': 'Dalja dështoi. Provo përsëri.',

    'landing.skip': 'Te përmbajtja',
    'landing.benefits': 'Përparësitë e tua',
    'nav.main': 'Navigimi kryesor',
    'nav.mobile': 'Navigimi në telefon',
    'nav.search': 'Gjej servise',
    'nav.newRequest': 'Kërkesë e re',
    'nav.myRequests': 'Kërkesat e mia',
    'nav.favorites': 'Të preferuarat',
    'nav.privateUnavailable': 'Kjo pamje private nuk është ende e disponueshme.',
    'nav.garages': 'Për serviset',
    'nav.login': 'Hyr',
    'nav.register': 'Regjistrohu',
    'nav.open': 'Hap menynë',
    'nav.close': 'Mbyll menynë',
    'landing.pageTitle': 'Servisi yt në Kosovë. Para se të nisesh.',
    'landing.titleOne': 'Servisi yt',
    'landing.titleTwo': 'në Kosovë.',
    'landing.titleAccent': 'Para se të nisesh.',
    'landing.intro':
      'Gjej servise të përshtatshme, krahaso përvojat dhe planifiko riparimin me qetësi. Vendimi mbetet i yti.',
    'landing.checked': 'Të dhënat e biznesit të kontrolluara',
    'landing.experiences': 'Përvoja të dokumentuara të klientëve',
    'landing.vehicle': 'I përshtatshëm për automjetin tënd',
    'landing.request': 'Krijo kërkesën tani',
    'landing.free': 'Falas dhe pa detyrim',
    'landing.direct': 'Kërko drejtpërdrejt një servis',
    'landing.choiceLabel': 'Ti vendos.',
    'landing.choiceTitle': 'Servisi yt. Kontakti yt.',
    'landing.choiceBody': 'Zgjidh vetë dhe bisedo drejtpërdrejt.',
    'landing.timeTitle': 'Më shumë kohë për të rëndësishmet',
    'landing.timeBody': 'Kërko lehtë, planifiko me qetësi.',
    'landing.choiceBenefit': 'Zgjedhja që të përshtatet',
    'landing.choiceBenefitBody': 'Me përvoja të dokumentuara.',
    'landing.trustTitle': 'Besimi fillon me qartësi',
    'landing.trustBody': 'Të dhënat e biznesit dhe përvojat në një vend.',
    'landing.searchEyebrow': 'RRUGA JOTE DREJT SERVISIT TË DUHUR',
    'landing.searchTitle': 'Çfarë i duhet automjetit tënd?',
    'landing.searchBody':
      'Zgjidh shërbimin dhe një vend në Kosovë. Krahaso serviset e përshtatshme dhe vendos vetë kë të kontaktosh.',
    'landing.noAccount': 'Kërko dhe zgjidh kontaktin – pa llogari.',
    'landing.invalidPlace': 'Zgjidh një vend nga lista.',
    'landing.footer': 'Automjeti yt. Vendimi yt.',
  },
  en: {
    'account.title': 'My account',
    'account.notifications': 'Notifications',
    'account.notificationsUnavailable': 'Notifications are not available yet.',
    'account.logout': 'Sign out',
    'account.logoutError': 'Sign out failed. Please try again.',

    'landing.skip': 'Skip to content',
    'landing.benefits': 'Your benefits',
    'nav.main': 'Main navigation',
    'nav.mobile': 'Mobile navigation',
    'nav.search': 'Find garages',
    'nav.newRequest': 'New request',
    'nav.myRequests': 'My requests',
    'nav.favorites': 'Favorites',
    'nav.privateUnavailable': 'This private view is not available yet.',
    'nav.garages': 'For garages',
    'nav.login': 'Log in',
    'nav.register': 'Register',
    'nav.open': 'Open menu',
    'nav.close': 'Close menu',
    'landing.pageTitle': 'Your garage in Kosovo. Before you travel.',
    'landing.titleOne': 'Your garage',
    'landing.titleTwo': 'in Kosovo.',
    'landing.titleAccent': 'Before you travel.',
    'landing.intro':
      'Find suitable garages, compare experiences and plan your repair at your own pace. The choice stays yours.',
    'landing.checked': 'Company data checked',
    'landing.experiences': 'Documented customer experiences',
    'landing.vehicle': 'Suitable for your vehicle',
    'landing.request': 'Create a request',
    'landing.free': 'Free & no obligation',
    'landing.direct': 'Go straight to the garage search',
    'landing.choiceLabel': 'You decide.',
    'landing.choiceTitle': 'Your garage. Your contact.',
    'landing.choiceBody': 'Choose personally and discuss directly.',
    'landing.timeTitle': 'More time for what matters',
    'landing.timeBody': 'Search easily, plan at your own pace.',
    'landing.choiceBenefit': 'A choice that suits you',
    'landing.choiceBenefitBody': 'With documented experiences.',
    'landing.trustTitle': 'Trust starts with clarity',
    'landing.trustBody': 'Company information and experiences at a glance.',
    'landing.searchEyebrow': 'YOUR WAY TO THE RIGHT GARAGE',
    'landing.searchTitle': 'What does your vehicle need?',
    'landing.searchBody':
      'Choose a service and a place in Kosovo. Compare suitable garages and decide whom to contact.',
    'landing.noAccount': 'Search and choose a contact – without an account.',
    'landing.invalidPlace': 'Please choose a place from the list.',
    'landing.footer': 'Your vehicle. Your decision.',
  },
};
