import type { AppLanguage } from './i18n';

const de = {
  hero: 'Starke Werkstätten.',
  heroAccent: 'Stärkere Mobilität in Kosovo.',
  heroIntro: 'Gemeinsam für eine zuverlässige und transparente Werkstattlandschaft.',
  badge: 'Vertrauen. Qualität.',
  badgeDetail: 'Eine bessere Mobilität.',
  eyebrow: 'Werkstatt aufnehmen',
  title: 'In wenigen Schritten zum Prüfauftrag',
  intro:
    'Erstelle deinen privaten Entwurf. Erst nach Einreichung, Prüfung und Freigabe wird dein Profil öffentlich.',
  basics: 'Basisdaten & Standort',
  basicsHelp: 'Grundlegende Informationen zu deiner Werkstatt.',
  name: 'Werkstattname',
  namePlaceholder: 'z. B. Auto Service Prishtina',
  place: 'Ort',
  choose: 'Bitte auswählen',
  address: 'Genaue Betriebsadresse',
  street: 'Straße',
  number: 'Hausnummer',
  city: 'Ort in der Adresse',
  postal: 'Postleitzahl (optional)',
  directions: 'Standortbeschreibung (bei fehlender Hausnummer)',
  directionsPlaceholder: 'z. B. Rruga e Dardanisë 12, 10000 Prishtina',
  locationPending: 'Standort noch zu bestätigen',
  locationChecked: 'Standort bestätigt',
  locationHelp:
    'Adresse manuell eingeben. Die Entfernung wird erst nach bestätigter Werkstattposition als Luftlinie zum gewählten Suchort angezeigt.',
  contact: 'Kontakt für die Prüfung',
  contactHelp: 'Diese Angaben helfen uns bei Rückfragen und bleiben privat.',
  person: 'Ansprechpartner (privat)',
  phone: 'Telefon für die Prüfung (privat)',
  publicPhone: 'Öffentliches Telefon (optional)',
  capabilities: 'Leistungen & Spezialisierung',
  capabilitiesHelp: 'Hilf Kunden, deine Werkstatt einzuordnen. Mehrfachauswahl möglich.',
  services: 'Leistungen',
  makes: 'Fahrzeugmarken (optional)',
  languages: 'Sprachen',
  specializations: 'Spezialisierungen (optional)',
  brandsHelp: 'Keine Markenauswahl bedeutet markenoffen.',
  specializationHelp: 'Spezialisierungen sind Selbstauskünfte, keine Qualifikationsnachweise.',
  consent:
    'Ich stimme der Aufnahme meines Profils zur Prüfung zu. Ein Prüfkennzeichen ist keine Reparaturqualitätsgarantie.',
  save: 'Privaten Entwurf erstellen',
  update: 'Änderungen speichern',
  saving: 'Wird gespeichert …',
  saved:
    'Dein Entwurf ist privat gespeichert. Du kannst ihn erneut öffnen und separat zur Prüfung einreichen.',
  publicSaved:
    'Änderungen gespeichert. Dieses Profil ist bereits veröffentlicht; Ansprechpartner und Prüftelefon bleiben privat.',
  privateNote: 'Dein Profil bleibt bis zur Freigabe privat.',
  nextTitle: 'Was passiert danach?',
  nextIntro: 'Du bestimmst, wann dein Entwurf bereit ist.',
  step1: 'Entwurf speichern',
  step1Help: 'Ergänze und prüfe deine Angaben in Ruhe.',
  step2: 'Zur Prüfung einreichen',
  step2Help: 'Wir prüfen deine Angaben. Rückfragen werden vor der Freigabe geklärt.',
  step3: 'Freigabe',
  step3Help: 'Erst nach erfolgreicher Prüfung erscheint dein Profil in der Suche.',
  why: 'Warum AutoKosova?',
  why1: 'Passend gefunden werden',
  why1Help: 'Zeige Kunden in Kosovo, welche Leistungen du anbietest.',
  why2: 'Vertrauen schaffen',
  why2Help: 'Nachvollziehbare Unternehmensangaben helfen bei der Werkstattwahl.',
  why3: 'Klare Profildaten',
  why3Help: 'Leistungen, Marken und Spezialisierungen übersichtlich an einem Ort.',
  privacy: 'Dein Entwurf bleibt privat',
  privacyHelp:
    'Ansprechpartner und Prüftelefon bleiben intern. Freigegebene Betriebsangaben können später öffentlich erscheinen.',
  search: 'Optionen suchen',
  noOptions: 'Keine Optionen verfügbar.',
  noMatches: 'Keine passenden Optionen.',
  remove: 'Entfernen',
  clear: 'Auswahl zurücksetzen',
  close: 'Auswahl schließen',
  loading: 'Wird geladen …',
  catalogError: 'Auswahl konnte nicht geladen werden.',
  required: 'Bitte dieses Feld ausfüllen.',
  selectRequired: 'Bitte mindestens eine Option auswählen.',
  addressError: 'Bitte Straße und Ort sowie Hausnummer oder eine Standortbeschreibung angeben.',
  conflict: 'Adresse und ausgewählter Ort stimmen nicht überein. Bitte beide Angaben prüfen.',
  postalError: 'Bitte vier oder fünf Ziffern eingeben.',
  phoneError: 'Bitte eine gültige Telefonnummer mit mindestens drei Zeichen eingeben.',
  invalid: 'Bitte die markierten Felder prüfen.',
  error: 'Speichern fehlgeschlagen. Deine Eingaben bleiben erhalten. Bitte erneut versuchen.',
  duplicate:
    'Ein ähnliches Profil existiert bereits. Es wurde kein neuer Entwurf angelegt und keine Übernahme ausgelöst.',
  signIn: 'Bitte melde dich an. Deine Eingaben bleiben in diesem Fenster erhalten.',
  login: 'In neuem Tab anmelden',
  refresh: 'Anmeldung prüfen',
  ownDrafts: 'Meine Werkstattprofile',
  newDraft: 'Neuen Entwurf beginnen',
  open: 'Öffnen',
  reload: 'Gespeicherten Stand erneut öffnen',
  loadError: 'Das Profil konnte nicht geladen werden. Bitte erneut versuchen.',
  submit: 'Zur Prüfung einreichen',
  submitted: 'Dein Profil wurde zur Prüfung eingereicht. Es ist noch nicht öffentlich.',
  stateDraft: 'Privater Entwurf',
  statePending: 'In Prüfung',
  statePublished: 'Veröffentlicht',
  stateRejected: 'Überarbeitung nötig',
  stateSuspended: 'Gesperrt',
  discard: 'Ungespeicherte Änderungen verwerfen?',
  valuesInvalid:
    'Bitte nur verfügbare Optionen wählen. Vorhandene eigene Angaben dürfen erhalten bleiben.',
};
type Copy = Record<keyof typeof de, string>;
const en: Copy = {
  hero: 'Strong garages.',
  heroAccent: 'Better mobility in Kosovo.',
  heroIntro: 'Together for reliable and transparent garage services.',
  badge: 'Trust. Quality.',
  badgeDetail: 'Better mobility.',
  eyebrow: 'Register a garage',
  title: 'Your garage. A clear start.',
  intro:
    'Create your private draft. Your profile becomes public only after submission, review and approval.',
  basics: 'Basic details & location',
  basicsHelp: 'The essentials about your garage.',
  name: 'Garage name',
  namePlaceholder: 'e.g. Auto Service Prishtina',
  place: 'Municipality',
  choose: 'Please select',
  address: 'Exact business address',
  street: 'Street',
  number: 'House number',
  city: 'Town in the address',
  postal: 'Postal code (optional)',
  directions: 'Location description (if there is no house number)',
  directionsPlaceholder: 'e.g. Rruga e Dardanisë 12, 10000 Prishtina',
  locationPending: 'Location awaiting confirmation',
  locationChecked: 'Location confirmed',
  locationHelp:
    'Enter the address manually. Straight-line distance to the selected search town appears only after the garage position is confirmed.',
  contact: 'Contact for verification',
  contactHelp: 'These details help with questions and remain private.',
  person: 'Contact person (private)',
  phone: 'Verification phone (private)',
  publicPhone: 'Public phone (optional)',
  capabilities: 'Services & specializations',
  capabilitiesHelp: 'Help customers understand your garage. Select more than one option.',
  services: 'Services',
  makes: 'Vehicle makes (optional)',
  languages: 'Languages',
  specializations: 'Specializations (optional)',
  brandsHelp: 'No makes selected means all makes welcome.',
  specializationHelp: 'Specializations are self-reported, not verified qualifications.',
  consent:
    'I agree to submit my profile for review. A verification badge is not a guarantee of repair quality.',
  save: 'Create private draft',
  update: 'Save changes',
  saving: 'Saving …',
  saved: 'Your draft is saved privately. You can reopen it and submit it for review separately.',
  publicSaved:
    'Changes saved. This profile is already public; the contact person and verification phone remain private.',
  privateNote: 'Your profile stays private until approval.',
  nextTitle: 'What happens next?',
  nextIntro: 'You decide when your draft is ready.',
  step1: 'Save your draft',
  step1Help: 'Take your time to complete and check your details.',
  step2: 'Submit for review',
  step2Help: 'We check your information. Questions are resolved before approval.',
  step3: 'Approval',
  step3Help: 'Your profile appears in search only after successful review.',
  why: 'Why AutoKosova?',
  why1: 'Help customers find you',
  why1Help: 'Show customers in Kosovo which services you provide.',
  why2: 'Build trust',
  why2Help: 'Clear company information helps customers choose a garage.',
  why3: 'Clear profile details',
  why3Help: 'Services, makes and specializations in one place.',
  privacy: 'Your draft stays private',
  privacyHelp:
    'The contact person and verification phone remain internal. Approved business details may later appear publicly.',
  search: 'Search options',
  noOptions: 'No options available.',
  noMatches: 'No matching options.',
  remove: 'Remove',
  clear: 'Clear selection',
  close: 'Close selection',
  loading: 'Loading …',
  catalogError: 'Options could not be loaded.',
  required: 'Please fill in this field.',
  selectRequired: 'Please select at least one option.',
  addressError: 'Enter a street and town, plus a house number or location description.',
  conflict: 'The address and selected municipality do not match. Please check both.',
  postalError: 'Please enter four or five digits.',
  phoneError: 'Please enter a valid phone number with at least three characters.',
  invalid: 'Please check the highlighted fields.',
  error: 'Could not save. Your input is retained. Please try again.',
  duplicate:
    'A similar profile already exists. No draft was created and no ownership transfer was started.',
  signIn: 'Please sign in. Your input stays in this window.',
  login: 'Sign in in a new tab',
  refresh: 'Check sign-in',
  ownDrafts: 'My garage profiles',
  newDraft: 'Start a new draft',
  open: 'Open',
  reload: 'Reopen saved version',
  loadError: 'The profile could not be loaded. Please try again.',
  submit: 'Submit for review',
  submitted: 'Your profile was submitted for review. It is not public yet.',
  stateDraft: 'Private draft',
  statePending: 'Under review',
  statePublished: 'Published',
  stateRejected: 'Changes needed',
  stateSuspended: 'Suspended',
  discard: 'Discard unsaved changes?',
  valuesInvalid: 'Please choose available options. Existing custom values may be kept.',
};
const sq: Copy = {
  hero: 'Servise të forta.',
  heroAccent: 'Mobilitet më i mirë në Kosovë.',
  heroIntro: 'Së bashku për shërbime të besueshme dhe transparente.',
  badge: 'Besim. Cilësi.',
  badgeDetail: 'Mobilitet më i mirë.',
  eyebrow: 'Regjistro servisin',
  title: 'Servisi yt. Një fillim i qartë.',
  intro:
    'Krijo draftin privat. Profili bëhet publik vetëm pas dorëzimit, kontrollit dhe miratimit.',
  basics: 'Të dhënat bazë & vendndodhja',
  basicsHelp: 'Informacionet kryesore për servisin tënd.',
  name: 'Emri i servisit',
  namePlaceholder: 'p.sh. Auto Service Prishtina',
  place: 'Komuna',
  choose: 'Zgjidh',
  address: 'Adresa e saktë e biznesit',
  street: 'Rruga',
  number: 'Numri i objektit',
  city: 'Qyteti në adresë',
  postal: 'Kodi postar (opsional)',
  directions: 'Përshkrimi i vendndodhjes (kur mungon numri)',
  directionsPlaceholder: 'p.sh. Rruga e Dardanisë 12, 10000 Prishtina',
  locationPending: 'Vendndodhja pret konfirmim',
  locationChecked: 'Vendndodhja e konfirmuar',
  locationHelp:
    'Shkruaj adresën manualisht. Distanca ajrore nga qyteti i kërkimit shfaqet vetëm pas konfirmimit të pozicionit të servisit.',
  contact: 'Kontakti për verifikim',
  contactHelp: 'Këto të dhëna ndihmojnë për sqarime dhe mbeten private.',
  person: 'Personi kontaktues (privat)',
  phone: 'Telefoni për verifikim (privat)',
  publicPhone: 'Telefoni publik (opsional)',
  capabilities: 'Shërbimet & specializimet',
  capabilitiesHelp: 'Ndihmo klientët të njohin servisin. Mund të zgjedhësh disa opsione.',
  services: 'Shërbimet',
  makes: 'Markat e automjeteve (opsionale)',
  languages: 'Gjuhët',
  specializations: 'Specializimet (opsionale)',
  brandsHelp: 'Pa marka të zgjedhura do të thotë të gjitha markat.',
  specializationHelp: 'Specializimet janë vetëdeklarime, jo kualifikime të verifikuara.',
  consent:
    'Pajtohem me regjistrimin e profilit për kontroll. Shenja e verifikimit nuk garanton cilësinë e riparimit.',
  save: 'Krijo draft privat',
  update: 'Ruaj ndryshimet',
  saving: 'Duke ruajtur …',
  saved: 'Drafti u ruajt privatisht. Mund ta rihapësh dhe ta dërgosh veçmas për kontroll.',
  publicSaved:
    'Ndryshimet u ruajtën. Profili është publik; personi kontaktues dhe telefoni i verifikimit mbeten privatë.',
  privateNote: 'Profili mbetet privat deri në miratim.',
  nextTitle: 'Çfarë ndodh më pas?',
  nextIntro: 'Ti vendos kur drafti është gati.',
  step1: 'Ruaj draftin',
  step1Help: 'Plotëso dhe kontrollo të dhënat me qetësi.',
  step2: 'Dërgo për kontroll',
  step2Help: 'Ne kontrollojmë të dhënat dhe sqarojmë pyetjet para miratimit.',
  step3: 'Miratimi',
  step3Help: 'Profili shfaqet në kërkim vetëm pas kontrollit të suksesshëm.',
  why: 'Pse AutoKosova?',
  why1: 'Klientët të gjejnë më lehtë',
  why1Help: 'Trego shërbimet që ofron për klientët në Kosovë.',
  why2: 'Krijo besim',
  why2Help: 'Të dhënat e qarta të biznesit ndihmojnë në zgjedhjen e servisit.',
  why3: 'Profil i qartë',
  why3Help: 'Shërbimet, markat dhe specializimet në një vend.',
  privacy: 'Drafti yt mbetet privat',
  privacyHelp:
    'Personi kontaktues dhe telefoni i verifikimit mbeten të brendshëm. Të dhënat e miratuara të biznesit mund të bëhen publike.',
  search: 'Kërko opsione',
  noOptions: 'Nuk ka opsione.',
  noMatches: 'Nuk ka opsione që përputhen.',
  remove: 'Hiq',
  clear: 'Pastro zgjedhjen',
  close: 'Mbyll zgjedhjen',
  loading: 'Duke ngarkuar …',
  catalogError: 'Opsionet nuk u ngarkuan.',
  required: 'Plotëso këtë fushë.',
  selectRequired: 'Zgjidh të paktën një opsion.',
  addressError: 'Shkruaj rrugën, qytetin dhe numrin ose përshkrimin e vendndodhjes.',
  conflict: 'Adresa nuk përputhet me komunën e zgjedhur. Kontrollo të dyja.',
  postalError: 'Shkruaj katër ose pesë shifra.',
  phoneError: 'Shkruaj një numër telefoni të vlefshëm me të paktën tre shenja.',
  invalid: 'Kontrollo fushat e shënuara.',
  error: 'Ruajtja dështoi. Të dhënat mbeten. Provo përsëri.',
  duplicate:
    'Ekziston një profil i ngjashëm. Nuk u krijua draft i ri dhe nuk u nis marrja e pronësisë.',
  signIn: 'Identifikohu. Të dhënat mbeten në këtë dritare.',
  login: 'Identifikohu në skedë të re',
  refresh: 'Kontrollo identifikimin',
  ownDrafts: 'Profilet e mia të serviseve',
  newDraft: 'Fillo draft të ri',
  open: 'Hap',
  reload: 'Rihap versionin e ruajtur',
  loadError: 'Profili nuk u ngarkua. Provo përsëri.',
  submit: 'Dërgo për kontroll',
  submitted: 'Profili u dërgua për kontroll. Ende nuk është publik.',
  stateDraft: 'Draft privat',
  statePending: 'Në kontroll',
  statePublished: 'Publikuar',
  stateRejected: 'Duhen ndryshime',
  stateSuspended: 'Pezulluar',
  discard: 'Të hidhen ndryshimet e paruajtura?',
  valuesInvalid: 'Zgjidh opsionet e disponueshme. Të dhënat ekzistuese mund të ruhen.',
};
export const onboardingCopy: Record<AppLanguage, Copy> = { de, en, sq };

export const garageOptionLabels: Record<AppLanguage, Readonly<Record<string, string>>> = {
  de: {
    Deutsch: 'Deutsch',
    Shqip: 'Albanisch',
    English: 'Englisch',
    Srpski: 'Serbisch',
    Türkçe: 'Türkisch',
    Italiano: 'Italienisch',
  },
  en: {
    Deutsch: 'German',
    Shqip: 'Albanian',
    English: 'English',
    Srpski: 'Serbian',
    Türkçe: 'Turkish',
    Italiano: 'Italian',
    Elektrodiagnose: 'Electrical diagnostics',
    Bremsen: 'Brakes',
    Reifenwechsel: 'Tire change',
    Klimaanlage: 'Air conditioning',
    Karosserie: 'Bodywork',
    Motor: 'Engine',
    Getriebe: 'Transmission',
    Inspektion: 'Inspection',
  },
  sq: {
    Deutsch: 'Gjermanisht',
    Shqip: 'Shqip',
    English: 'Anglisht',
    Srpski: 'Serbisht',
    Türkçe: 'Turqisht',
    Italiano: 'Italisht',
    Elektrodiagnose: 'Diagnostikë elektrike',
    Bremsen: 'Frena',
    Reifenwechsel: 'Ndërrim gomash',
    Klimaanlage: 'Kondicioner',
    Karosserie: 'Karroceri',
    Motor: 'Motor',
    Getriebe: 'Kambio',
    Inspektion: 'Kontroll',
  },
};
