import type { AppLanguage } from './i18n';

export const profileCopy: Readonly<Record<AppLanguage, Readonly<Record<string, string>>>> = {
  de: {
    'profile.ui.home': 'Startseite',
    'profile.ui.share': 'Teilen',
    'profile.ui.shareTitle': 'Werkstattprofil teilen',
    'profile.ui.shareBody': 'Der Link enthält nur die öffentliche Profiladresse.',
    'profile.ui.shareUrlLabel': 'Öffentliche Profiladresse',
    'profile.ui.copyLink': 'Link kopieren',
    'profile.ui.copied': 'Link kopiert.',
    'profile.ui.copyFailed': 'Kopiere den markierten Link manuell.',
    'profile.ui.close': 'Schließen',
    'profile.ui.previousPhoto': 'Vorheriges Foto',
    'profile.ui.nextPhoto': 'Nächstes Foto',
    'profile.ui.photoOf': 'Veröffentlichtes Foto von {garage}',
    'profile.ui.photoPosition': 'Foto {current} von {total}',
    'profile.ui.allPhotos': 'Alle Fotos anzeigen ({count})',
    'profile.ui.noPhotosTitle': 'Noch keine Fotos veröffentlicht',
    'profile.ui.noPhotosBody': 'Das Profil bleibt mit allen freigegebenen Angaben nutzbar.',
    'profile.ui.neutralLogo': 'Neutraler Platzhalter für {garage}',
    'profile.ui.about': 'Über uns',
    'profile.ui.reviews': 'Bewertungen',
    'profile.ui.services': 'Leistungen',
    'profile.ui.makes': 'Marken',
    'profile.ui.location': 'Standort',
    'profile.ui.photos': 'Fotos',
    'profile.ui.ratingCount': '{count} Bewertungen',
    'profile.ui.ratingCountOne': '{count} Bewertung',
    'profile.ui.outOfFive': 'von 5',
    'profile.ui.contact': 'Kontakt aufnehmen',
    'profile.ui.contactShort': 'Schnell und unverbindlich',
    'profile.ui.favorite': 'Zu Favoriten',
    'profile.ui.favoriteSaved': 'Favorit gespeichert',
    'profile.ui.popularServices': 'Leistungen',
    'profile.ui.selfReported': 'Selbstauskunft der Werkstatt',
    'profile.ui.allMakes': 'Alle Marken',
    'profile.ui.allMakesBody': 'Keine Markenbeschränkung veröffentlicht.',
    'profile.ui.noSpecializations': 'Keine Spezialisierung veröffentlicht',
    'profile.ui.languages': 'Sprachen',
    'profile.ui.locationIn': 'Standort in {place}',
    'profile.ui.distance': '{distance} km Luftlinie zu {place}',
    'profile.ui.locationUnconfirmed':
      'Eine Entfernung erscheint nur beim Aufruf aus einer Ortssuche.',
    'profile.ui.originalText': 'Originaltext der Werkstatt, nicht übersetzt.',
    'profile.ui.reviewIntro': 'Nur veröffentlichte Erfahrungen mit geprüftem Werkstattbesuch.',
    'profile.ui.reviewVisit': 'Besuch {month}',
    'profile.ui.verifiedVisit': 'Werkstattbesuch belegt',
    'profile.ui.ratingDetails':
      'Arbeitsqualität {work}/5 · Kommunikation {communication}/5 · Preistransparenz {price}/5 · Termintreue {punctuality}/5',
    'profile.ui.response': 'Öffentliche Antwort der Werkstatt',
    'profile.ui.updates': 'Nachvollziehbare Updates',
    'profile.ui.complaint': 'Reklamation',
    'profile.ui.rework': 'Nacharbeit',
    'profile.ui.filter': 'Bewertungen filtern',
    'profile.ui.writeUnavailable':
      'Die Bewertungsfunktion ist in dieser Ansicht noch nicht verfügbar. Wir zeigen kein Formular ohne angebundenen Nachweis- und Speicherprozess.',
    'profile.ui.contactDialog': 'Kontakt zu {garage}',
    'profile.ui.contactDialogBody':
      'Wähle WhatsApp oder Telefon selbst. AutoKosova sendet keine Nachricht und bestätigt keinen Auftrag oder Termin.',
    'profile.ui.includeDetails': 'Eigene Angaben in den Entwurf aufnehmen',
    'profile.ui.vehicle': 'Fahrzeug (optional)',
    'profile.ui.vehiclePlaceholder': 'Zum Beispiel: Škoda Octavia, 2018',
    'profile.ui.concern': 'Anliegen (optional)',
    'profile.ui.concernPlaceholder': 'Zum Beispiel: Bremsen prüfen lassen',
    'profile.ui.messageDraft': 'Nachrichtenentwurf',
    'profile.ui.whatsapp': 'In WhatsApp öffnen',
    'profile.ui.call': 'Anrufen',
    'profile.ui.contactFallback': 'Falls WhatsApp nicht verfügbar ist, kannst du direkt anrufen.',
    'profile.ui.noContact': 'Keine gültige öffentliche Telefonnummer verfügbar.',
    'profile.ui.demoContact':
      'Lokale Demo: Vorschau und Links sind prüfbar, externe Apps werden nicht geöffnet.',
    'profile.ui.backToResults': 'Zurück zu den Suchergebnissen',
  },
  sq: {
    'profile.ui.home': 'Ballina',
    'profile.ui.share': 'Shpërndaje',
    'profile.ui.shareTitle': 'Shpërndaje profilin e servisit',
    'profile.ui.shareBody': 'Lidhja përmban vetëm adresën publike të profilit.',
    'profile.ui.shareUrlLabel': 'Adresa publike e profilit',
    'profile.ui.copyLink': 'Kopjo lidhjen',
    'profile.ui.copied': 'Lidhja u kopjua.',
    'profile.ui.copyFailed': 'Kopjo manualisht lidhjen e shënuar.',
    'profile.ui.close': 'Mbyll',
    'profile.ui.previousPhoto': 'Fotoja e mëparshme',
    'profile.ui.nextPhoto': 'Fotoja tjetër',
    'profile.ui.photoOf': 'Foto e publikuar nga {garage}',
    'profile.ui.photoPosition': 'Fotoja {current} nga {total}',
    'profile.ui.allPhotos': 'Shfaq të gjitha fotot ({count})',
    'profile.ui.noPhotosTitle': 'Ende nuk ka foto të publikuara',
    'profile.ui.noPhotosBody': 'Profili mbetet i përdorshëm me të gjitha të dhënat e publikuara.',
    'profile.ui.neutralLogo': 'Simbol neutral për {garage}',
    'profile.ui.about': 'Rreth nesh',
    'profile.ui.reviews': 'Vlerësimet',
    'profile.ui.services': 'Shërbimet',
    'profile.ui.makes': 'Markat',
    'profile.ui.location': 'Vendndodhja',
    'profile.ui.photos': 'Fotot',
    'profile.ui.ratingCount': '{count} vlerësime',
    'profile.ui.ratingCountOne': '{count} vlerësim',
    'profile.ui.outOfFive': 'nga 5',
    'profile.ui.contact': 'Kontakto',
    'profile.ui.contactShort': 'Shpejt dhe pa detyrim',
    'profile.ui.favorite': 'Shto te të preferuarat',
    'profile.ui.favoriteSaved': 'U ruajt te të preferuarat',
    'profile.ui.popularServices': 'Shërbimet',
    'profile.ui.selfReported': 'Vetëdeklarim i servisit',
    'profile.ui.allMakes': 'Të gjitha markat e automjeteve',
    'profile.ui.allMakesBody': 'Nuk është publikuar asnjë kufizim i markave.',
    'profile.ui.noSpecializations': 'Nuk ka specializim të publikuar',
    'profile.ui.languages': 'Gjuhët',
    'profile.ui.locationIn': 'Vendndodhja në {place}',
    'profile.ui.distance': '{distance} km vijë ajrore nga {place}',
    'profile.ui.locationUnconfirmed':
      'Distanca shfaqet vetëm kur profili hapet nga një kërkim me vend.',
    'profile.ui.originalText': 'Teksti origjinal i servisit, i papërkthyer.',
    'profile.ui.reviewIntro': 'Vetëm përvoja të publikuara me vizitë të kontrolluar në servis.',
    'profile.ui.reviewVisit': 'Vizita {month}',
    'profile.ui.verifiedVisit': 'Vizita në servis e dëshmuar',
    'profile.ui.ratingDetails':
      'Cilësia {work}/5 · Komunikimi {communication}/5 · Transparenca e çmimit {price}/5 · Përpikëria {punctuality}/5',
    'profile.ui.response': 'Përgjigjja publike e servisit',
    'profile.ui.updates': 'Përditësime të gjurmueshme',
    'profile.ui.complaint': 'Ankesë',
    'profile.ui.rework': 'Riparim pasues',
    'profile.ui.filter': 'Filtro vlerësimet',
    'profile.ui.writeUnavailable':
      'Funksioni i vlerësimit nuk është ende i disponueshëm në këtë faqe. Nuk shfaqim formular pa proces të lidhur të dëshmisë dhe ruajtjes.',
    'profile.ui.contactDialog': 'Kontakto {garage}',
    'profile.ui.contactDialogBody':
      'Zgjidh vetë WhatsApp ose telefonin. AutoKosova nuk dërgon mesazh dhe nuk konfirmon porosi ose termin.',
    'profile.ui.includeDetails': 'Shto të dhënat e mia në draft',
    'profile.ui.vehicle': 'Automjeti (opsional)',
    'profile.ui.vehiclePlaceholder': 'Për shembull: Škoda Octavia, 2018',
    'profile.ui.concern': 'Çështja (opsionale)',
    'profile.ui.concernPlaceholder': 'Për shembull: kontrollo frenat',
    'profile.ui.messageDraft': 'Drafti i mesazhit',
    'profile.ui.whatsapp': 'Hape në WhatsApp',
    'profile.ui.call': 'Telefono',
    'profile.ui.contactFallback':
      'Nëse WhatsApp nuk është i disponueshëm, mund të telefonosh drejtpërdrejt.',
    'profile.ui.noContact': 'Nuk ka numër publik telefoni të vlefshëm.',
    'profile.ui.demoContact':
      'Demo lokale: drafti dhe lidhjet mund të testohen, por aplikacionet e jashtme nuk hapen.',
    'profile.ui.backToResults': 'Kthehu te rezultatet',
  },
  en: {
    'profile.ui.home': 'Home',
    'profile.ui.share': 'Share',
    'profile.ui.shareTitle': 'Share garage profile',
    'profile.ui.shareBody': 'The link contains only the public profile address.',
    'profile.ui.shareUrlLabel': 'Public profile address',
    'profile.ui.copyLink': 'Copy link',
    'profile.ui.copied': 'Link copied.',
    'profile.ui.copyFailed': 'Copy the selected link manually.',
    'profile.ui.close': 'Close',
    'profile.ui.previousPhoto': 'Previous photo',
    'profile.ui.nextPhoto': 'Next photo',
    'profile.ui.photoOf': 'Published photo from {garage}',
    'profile.ui.photoPosition': 'Photo {current} of {total}',
    'profile.ui.allPhotos': 'Show all photos ({count})',
    'profile.ui.noPhotosTitle': 'No photos published yet',
    'profile.ui.noPhotosBody': 'The profile remains usable with all published details.',
    'profile.ui.neutralLogo': 'Neutral placeholder for {garage}',
    'profile.ui.about': 'About us',
    'profile.ui.reviews': 'Reviews',
    'profile.ui.services': 'Services',
    'profile.ui.makes': 'Makes',
    'profile.ui.location': 'Location',
    'profile.ui.photos': 'Photos',
    'profile.ui.ratingCount': '{count} reviews',
    'profile.ui.ratingCountOne': '{count} review',
    'profile.ui.outOfFive': 'out of 5',
    'profile.ui.contact': 'Contact',
    'profile.ui.contactShort': 'Quick and without obligation',
    'profile.ui.favorite': 'Add to favorites',
    'profile.ui.favoriteSaved': 'Saved to favorites',
    'profile.ui.popularServices': 'Services',
    'profile.ui.selfReported': 'Garage self-description',
    'profile.ui.allMakes': 'All vehicle makes',
    'profile.ui.allMakesBody': 'No make restriction has been published.',
    'profile.ui.noSpecializations': 'No specialization published',
    'profile.ui.languages': 'Languages',
    'profile.ui.locationIn': 'Located in {place}',
    'profile.ui.distance': '{distance} km straight-line distance from {place}',
    'profile.ui.locationUnconfirmed':
      'A distance appears only when the profile is opened from a location search.',
    'profile.ui.originalText': 'Original garage text, not translated.',
    'profile.ui.reviewIntro': 'Only published experiences with a verified garage visit.',
    'profile.ui.reviewVisit': 'Visit {month}',
    'profile.ui.verifiedVisit': 'Garage visit verified',
    'profile.ui.ratingDetails':
      'Work quality {work}/5 · Communication {communication}/5 · Price transparency {price}/5 · Punctuality {punctuality}/5',
    'profile.ui.response': 'Public response from the garage',
    'profile.ui.updates': 'Traceable updates',
    'profile.ui.complaint': 'Complaint',
    'profile.ui.rework': 'Follow-up work',
    'profile.ui.filter': 'Filter reviews',
    'profile.ui.writeUnavailable':
      'Review submission is not available from this page yet. We do not show a form without a connected evidence and storage flow.',
    'profile.ui.contactDialog': 'Contact {garage}',
    'profile.ui.contactDialogBody':
      'Choose WhatsApp or phone yourself. AutoKosova does not send a message or confirm a job or appointment.',
    'profile.ui.includeDetails': 'Include my own details in the draft',
    'profile.ui.vehicle': 'Vehicle (optional)',
    'profile.ui.vehiclePlaceholder': 'For example: Škoda Octavia, 2018',
    'profile.ui.concern': 'Request (optional)',
    'profile.ui.concernPlaceholder': 'For example: inspect the brakes',
    'profile.ui.messageDraft': 'Message draft',
    'profile.ui.whatsapp': 'Open in WhatsApp',
    'profile.ui.call': 'Call',
    'profile.ui.contactFallback': 'If WhatsApp is unavailable, you can call directly.',
    'profile.ui.noContact': 'No valid public phone number is available.',
    'profile.ui.demoContact':
      'Local demo: the draft and links can be tested, but external apps do not open.',
    'profile.ui.backToResults': 'Back to search results',
  },
};
