export const requestCopy = {
  de: {
    title: 'Anfrage erstellen',
    vehicle: 'Dein Fahrzeug',
    repair: 'Reparatur',
    hero: 'Deine Anfrage.\nIn besten Händen.',
    intro:
      'Beschreibe deinen Bedarf, finde passende Werkstätten in Kosovo und kontaktiere sie selbst.',
    subtitle: 'Einfach, klar, strukturiert – Schritt für Schritt zur passenden Werkstatt.',
    vehicleHelp: 'Alle Fahrzeugangaben sind optional. Ergänze, was du weißt.',
    details: 'Details',
    done: 'Fertig',
    steps: 'Schritte',
    car: 'PKW',
    suv: 'SUV',
    van: 'Transporter',
    camper: 'Wohnmobil',
    motorcycle: 'Motorrad',
    class: 'Fahrzeugklasse (optional)',
    make: 'Marke',
    model: 'Modell',
    year: 'Baujahr',
    engine: 'Motorisierung',
    fuel: 'Kraftstoff',
    transmission: 'Getriebe',
    manual: 'Schaltgetriebe',
    automatic: 'Automatik',
    semiAutomatic: 'Halbautomatik',
    mileage: 'Kilometerstand (optional)',
    petrol: 'Benzin',
    diesel: 'Diesel',
    hybrid: 'Hybrid',
    electric: 'Elektro',
    lpg: 'Autogas',
    other: 'Andere',
    problem: 'Problem oder gewünschte Arbeit',
    service: 'Leistung',
    symptom: 'Symptome oder Hinweis (optional)',
    placeTime: 'Ort & Zeit',
    travelHelp:
      'Ein bis drei verschiedene Orte, jeweils 5–100 km Luftlinie. Reisedaten bleiben privat.',
    place: 'Ort',
    radius: 'Radius in km',
    remove: 'Entfernen',
    addPlace: 'Weiteren Ort hinzufügen',
    dropoff: 'Früheste Abgabe',
    pickup: 'Späteste Abholung',
    stayEnd: 'Aufenthaltsende',
    attachments: 'Fotos oder Diagnosebericht (optional)',
    uploadHelp:
      'Ohne angebundenen Dateispeicher werden Dateien nur lokal ausgewählt und nicht hochgeladen oder mitgespeichert. Beim Neuladen geht die Dateiauswahl verloren.',
    chooseFiles: 'Dateien auswählen',
    localFiles: 'Nur lokal ausgewählte Dateien',
    nextHelp:
      'Die Suche übernimmt nur Leistung, Orte und Radien. Keine automatische Übermittlung an Werkstätten, keine Buchung.',
    summary: 'Deine Zusammenfassung',
    noVehicle: 'Keine Fahrzeugangaben',
    draft: 'Browserentwurf – noch nicht dauerhaft gespeichert.',
    saved: 'Privat im Konto gespeichert. Lokal ausgewählte Dateien wurden nicht mitgespeichert.',
    save: 'Entwurf privat speichern',
    login: 'Anmelden zum Speichern',
    loginRequired:
      'Bitte melde dich zum dauerhaften Speichern an. Dein Browserentwurf bleibt erhalten.',
    saveError:
      'Speicherung nicht bestätigt. Dein Browserentwurf bleibt erhalten. Bitte versuche es erneut.',
    vehicleError:
      'Bitte prüfe deine Fahrzeugangaben: Baujahr 1886–2100, Kilometerstand 0–2.000.000, Texte höchstens 120 Zeichen. Alle Angaben sind optional.',
    serviceError: 'Bitte wähle eine Leistung. Symptome sind optional, höchstens 2.000 Zeichen.',
    travelError:
      'Bitte prüfe verschiedene Orte, ganze Radien von 5–100 km und die Datumsfolge: Abgabe ≤ Abholung ≤ Aufenthaltsende.',
    fileError: 'Höchstens 5 PDF-, JPG- oder PNG-Dateien, jeweils 1 Byte bis 10 MB.',
    why: 'Warum AutoKosova?',
    benefit1: 'Schnell zur passenden Werkstatt',
    benefit1Help: 'Strukturiert suchen nach Leistung und Ort.',
    benefit2: 'Spezialisierung in deiner Region',
    benefit2Help: 'Leistungen und Unternehmensprüfung sind im Profil erkennbar.',
    benefit3: 'Erfahrungen transparent einordnen',
    benefit3Help: 'Bewertungen werden als Erfahrungen gezeigt. Keine Reparaturgarantie.',
    benefit4: 'Kostenlos und unverbindlich suchen',
    benefit4Help: 'Du wählst selbst, wen du kontaktierst.',
    privacy: 'Deine Angaben bleiben privat',
    privacyHelp:
      'Der Entwurf bleibt im Browser. Dauerhaftes Speichern erfolgt nur über dein Konto. Keine automatische Weitergabe an Werkstätten.',
    footer1: 'Mehr Zeit für das Wesentliche',
    footer2: 'Selbst auswählen und kontaktieren',
    footer3: 'Klare Angaben statt Versprechen',
  },
  sq: {
    title: 'Krijo kërkesën',
    vehicle: 'Automjeti yt',
    repair: 'Riparimi',
    hero: 'Kërkesa jote.\nNë duar të mira.',
    intro: 'Përshkruaj nevojën tënde, gjej servise të përshtatshme në Kosovë dhe kontaktoji vetë.',
    subtitle: 'Thjesht, qartë, me radhë – hap pas hapi drejt servisit të duhur.',
    vehicleHelp: 'Të gjitha të dhënat e automjetit janë opsionale. Plotëso ato që di.',
    details: 'Detaje',
    done: 'Përfundimi',
    steps: 'Hapat',
    car: 'Veturë',
    suv: 'SUV',
    van: 'Furgon',
    camper: 'Autokamp',
    motorcycle: 'Motoçikletë',
    class: 'Lloji i automjetit (opsional)',
    make: 'Marka',
    model: 'Modeli',
    year: 'Viti',
    engine: 'Motori',
    fuel: 'Karburanti',
    transmission: 'Transmisioni',
    manual: 'Manual',
    automatic: 'Automatik',
    semiAutomatic: 'Gjysmëautomatik',
    mileage: 'Kilometrat (opsionale)',
    petrol: 'Benzinë',
    diesel: 'Naftë',
    hybrid: 'Hibrid',
    electric: 'Elektrik',
    lpg: 'Gaz',
    other: 'Tjetër',
    problem: 'Problemi ose puna e dëshiruar',
    service: 'Shërbimi',
    symptom: 'Simptoma ose shënime (opsionale)',
    placeTime: 'Vendi & koha',
    travelHelp:
      'Një deri në tre vende të ndryshme, secili me rreze ajrore 5–100 km. Datat e udhëtimit mbeten private.',
    place: 'Vendi',
    radius: 'Rrezja në km',
    remove: 'Hiq',
    addPlace: 'Shto një vend tjetër',
    dropoff: 'Dorëzimi më i hershëm',
    pickup: 'Marrja më e vonshme',
    stayEnd: 'Fundi i qëndrimit',
    attachments: 'Foto ose raport diagnostik (opsionale)',
    uploadHelp:
      'Pa ruajtje të lidhur të skedarëve, skedarët zgjidhen vetëm lokalisht dhe nuk ngarkohen apo ruhen. Zgjedhja humbet kur ringarkohet faqja.',
    chooseFiles: 'Zgjidh skedarë',
    localFiles: 'Skedarë të zgjedhur vetëm lokalisht',
    nextHelp:
      'Kërkimi përdor vetëm shërbimin, vendet dhe rrezet. Asnjë dërgim automatik te serviset, asnjë rezervim.',
    summary: 'Përmbledhja jote',
    noVehicle: 'Pa të dhëna automjeti',
    draft: 'Draft në shfletues – ende i paruajtur përgjithmonë.',
    saved: 'U ruajt privatisht në llogari. Skedarët lokalë nuk u ruajtën.',
    save: 'Ruaje draftin privatisht',
    login: 'Hyr për të ruajtur',
    loginRequired: 'Hyr për ta ruajtur përgjithmonë. Drafti në shfletues ruhet.',
    saveError: 'Ruajtja nuk u konfirmua. Drafti në shfletues ruhet. Provo përsëri.',
    vehicleError:
      'Kontrollo të dhënat: viti 1886–2100, kilometrat 0–2.000.000, tekstet deri në 120 karaktere. Të gjitha janë opsionale.',
    serviceError: 'Zgjidh një shërbim. Simptomat janë opsionale, deri në 2.000 karaktere.',
    travelError:
      'Kontrollo vendet e ndryshme, rrezet e plota 5–100 km dhe datat: dorëzimi ≤ marrja ≤ fundi i qëndrimit.',
    fileError: 'Deri në 5 skedarë PDF, JPG ose PNG, secili nga 1 bajt deri në 10 MB.',
    why: 'Pse AutoKosova?',
    benefit1: 'Shpejt te servisi i duhur',
    benefit1Help: 'Kërko sipas shërbimit dhe vendit.',
    benefit2: 'Specializim në rajonin tënd',
    benefit2Help: 'Shërbimet dhe verifikimi i biznesit tregohen në profil.',
    benefit3: 'Vlerëso përvojat në mënyrë transparente',
    benefit3Help: 'Vlerësimet tregojnë përvoja. Nuk janë garanci riparimi.',
    benefit4: 'Kërko falas dhe pa detyrim',
    benefit4Help: 'Ti zgjedh kë kontakton.',
    privacy: 'Të dhënat e tua mbeten private',
    privacyHelp:
      'Drafti mbetet në shfletues. Ruajtja e përhershme bëhet vetëm në llogarinë tënde. Asnjë dërgim automatik te serviset.',
    footer1: 'Më shumë kohë për gjërat me rëndësi',
    footer2: 'Zgjidh dhe kontakto vetë',
    footer3: 'Të dhëna të qarta, jo premtime',
  },
  en: {
    title: 'Create a request',
    vehicle: 'Your vehicle',
    repair: 'Repair',
    hero: 'Your request.\nIn good hands.',
    intro: 'Describe what you need, find suitable workshops in Kosovo and contact them yourself.',
    subtitle: 'Simple, clear, structured – step by step to a suitable workshop.',
    vehicleHelp: 'All vehicle details are optional. Add what you know.',
    details: 'Details',
    done: 'Done',
    steps: 'Steps',
    car: 'Car',
    suv: 'SUV',
    van: 'Van',
    camper: 'Camper',
    motorcycle: 'Motorcycle',
    class: 'Vehicle class (optional)',
    make: 'Make',
    model: 'Model',
    year: 'Year',
    engine: 'Engine',
    fuel: 'Fuel',
    transmission: 'Transmission',
    manual: 'Manual',
    automatic: 'Automatic',
    semiAutomatic: 'Semi-automatic',
    mileage: 'Mileage (optional)',
    petrol: 'Petrol',
    diesel: 'Diesel',
    hybrid: 'Hybrid',
    electric: 'Electric',
    lpg: 'LPG',
    other: 'Other',
    problem: 'Problem or requested work',
    service: 'Service',
    symptom: 'Symptoms or notes (optional)',
    placeTime: 'Place & time',
    travelHelp:
      'One to three different places, each with a 5–100 km straight-line radius. Travel dates stay private.',
    place: 'Place',
    radius: 'Radius in km',
    remove: 'Remove',
    addPlace: 'Add another place',
    dropoff: 'Earliest drop-off',
    pickup: 'Latest pickup',
    stayEnd: 'End of stay',
    attachments: 'Photos or diagnostic report (optional)',
    uploadHelp:
      'Without connected file storage, files are selected locally only and are not uploaded or saved. Reloading clears the file selection.',
    chooseFiles: 'Choose files',
    localFiles: 'Locally selected files only',
    nextHelp:
      'Search uses only service, places and radii. No automatic sharing with workshops and no booking.',
    summary: 'Your summary',
    noVehicle: 'No vehicle details',
    draft: 'Browser draft – not saved permanently yet.',
    saved: 'Saved privately to your account. Locally selected files were not saved.',
    save: 'Save draft privately',
    login: 'Sign in to save',
    loginRequired: 'Please sign in to save permanently. Your browser draft is retained.',
    saveError: 'Saving was not confirmed. Your browser draft is retained. Please try again.',
    vehicleError:
      'Check vehicle details: year 1886–2100, mileage 0–2,000,000, text up to 120 characters. All fields are optional.',
    serviceError: 'Choose a service. Symptoms are optional, up to 2,000 characters.',
    travelError:
      'Check distinct places, whole radii of 5–100 km and dates: drop-off ≤ pickup ≤ end of stay.',
    fileError: 'Up to 5 PDF, JPG or PNG files, each from 1 byte to 10 MB.',
    why: 'Why AutoKosova?',
    benefit1: 'Find a suitable workshop quickly',
    benefit1Help: 'Search by service and location.',
    benefit2: 'Specialists in your area',
    benefit2Help: 'Profiles show services and business verification.',
    benefit3: 'Understand customer experiences',
    benefit3Help: 'Reviews describe experiences. They are not a repair guarantee.',
    benefit4: 'Search freely, without commitment',
    benefit4Help: 'You choose whom to contact.',
    privacy: 'Your details stay private',
    privacyHelp:
      'The draft stays in your browser. Permanent saving uses your account. Nothing is automatically sent to workshops.',
    footer1: 'More time for what matters',
    footer2: 'Choose and contact directly',
    footer3: 'Clear information over promises',
  },
} as const;
export type RequestCopyKey = keyof typeof requestCopy.de;
