import { accountNavigationCopy } from './account-navigation-copy';
import type { AppLanguage } from './i18n';
const labels: Readonly<Record<string, readonly [string, string, string]>> = {
  write: ['Bewertung schreiben', 'Write a review', 'Shkruaj një vlerësim'],
  own: [
    accountNavigationCopy('de').reviews,
    accountNavigationCopy('en').reviews,
    accountNavigationCopy('sq').reviews,
  ],
  intro: [
    'Berichte über einen tatsächlichen Werkstattbesuch. Dein Nachweis bleibt privat.',
    'Describe an actual garage visit. Your evidence stays private.',
    'Përshkruaj një vizitë reale në servis. Dëshmia mbetet private.',
  ],
  login: [
    'Bitte melde dich an, um deine Bewertung einzureichen.',
    'Sign in to submit your review.',
    'Hyr për të dorëzuar vlerësimin.',
  ],
  service: ['Ausgeführte Arbeit / Leistung', 'Work / service performed', 'Puna / shërbimi i kryer'],
  month: ['Besuchsmonat und Jahr', 'Visit month and year', 'Muaji dhe viti i vizitës'],
  make: ['Fahrzeugmarke (optional)', 'Vehicle make (optional)', 'Marka e automjetit (opsionale)'],
  text: ['Dein Erfahrungsbericht', 'Your experience', 'Përvoja jote'],
  textHelp: [
    '20–2000 Zeichen. Keine Telefonnummern, Adressen oder unnötigen personenbezogenen Angaben.',
    '20–2000 characters. Do not include phone numbers, addresses or unnecessary personal information.',
    '20–2000 karaktere. Pa numra telefoni, adresa ose të dhëna personale të panevojshme.',
  ],
  workQuality: ['Arbeitsqualität', 'Quality of work', 'Cilësia e punës'],
  communication: ['Kommunikation', 'Communication', 'Komunikimi'],
  priceTransparency: ['Preistransparenz', 'Price transparency', 'Transparenca e çmimit'],
  punctuality: ['Termintreue', 'Punctuality', 'Respektimi i afatit'],
  ratings: [
    'Bewertungskriterien – jeweils 1 bis 5 Sterne',
    'Rating criteria – 1 to 5 stars each',
    'Kriteret – nga 1 deri në 5 yje',
  ],
  overall: [
    'Gesamtwert: gleichgewichteter Mittelwert der vier Kriterien.',
    'Overall: equal-weight average of the four criteria.',
    'Gjithsej: mesatarja e barabartë e katër kritereve.',
  ],
  choose: ['Bitte auswählen', 'Please select', 'Zgjidh'],
  none: ['Keine Angabe', 'Not specified', 'Pa të dhëna'],
  evidence: ['Privater Besuchsnachweis', 'Private visit evidence', 'Dëshmi private e vizitës'],
  redact: [
    'Schwärze nicht benötigte personenbezogene Angaben vor einem echten Upload.',
    'Redact unnecessary personal information before any real upload.',
    'Mbulo të dhënat personale të panevojshme para ngarkimit real.',
  ],
  demo: [
    'Lokale Demo: Nur die bereitgestellte fiktive Textdatei wird angenommen (max. 4 KB). Keine echten Rechnungen hochladen. Die synthetische Freigabe ist kein Malware-Scan.',
    'Local demo: only the supplied fictional text file is accepted (max. 4 KB). Do not upload real invoices. Synthetic approval is not a malware scan.',
    'Demo lokale: pranohet vetëm skedari fiktiv i ofruar (maks. 4 KB). Mos ngarko fatura reale. Miratimi sintetik nuk është skanim për malware.',
  ],
  sample: [
    'Fiktiven Beispielnachweis speichern',
    'Save fictional sample evidence',
    'Ruaj dëshminë shembull fiktive',
  ],
  upload: ['Nachweis hochladen', 'Upload evidence', 'Ngarko dëshminë'],
  uploaded: [
    'Fiktiver Nachweis privat gespeichert. Noch keine Bewertung veröffentlicht.',
    'Fictional evidence stored privately. No review has been published.',
    'Dëshmia fiktive u ruajt privatisht. Vlerësimi ende nuk është publikuar.',
  ],
  uploadUnavailable: [
    'Private Uploads sind in dieser Umgebung nicht freigegeben. Es wird kein erfolgreicher Upload vorgetäuscht.',
    'Private uploads are not enabled in this environment. No successful upload is claimed.',
    'Ngarkimet private nuk janë aktivizuar këtu. Nuk pretendohet ngarkim i suksesshëm.',
  ],
  submit: ['Zur Prüfung einreichen', 'Submit for review', 'Dorëzo për shqyrtim'],
  submittedHelp: [
    'Deine Einreichung ist gespeichert. Erst nach unabhängiger Prüfung kann sie öffentlich erscheinen.',
    'Your submission is saved. Publication requires independent verification.',
    'Dorëzimi u ruajt. Publikimi kërkon verifikim të pavarur.',
  ],
  status: ['Bewertungsstatus', 'Review status', 'Statusi i vlerësimit'],
  evidenceStatus: ['Nachweisstatus', 'Evidence status', 'Statusi i dëshmisë'],
  caseStatus: ['Prüfvorgang', 'Verification case', 'Rasti i verifikimit'],
  submitted: ['Eingereicht', 'Submitted', 'Dorëzuar'],
  under_review: ['In Prüfung', 'Under review', 'Në shqyrtim'],
  assigned: ['In Prüfung', 'Assigned for review', 'Caktuar për shqyrtim'],
  published: ['Veröffentlicht', 'Published', 'Publikuar'],
  temporarily_hidden: ['Vorläufig ausgeblendet', 'Temporarily hidden', 'Fshehur përkohësisht'],
  rejected: ['Abgelehnt', 'Rejected', 'Refuzuar'],
  withdrawn: ['Zurückgezogen', 'Withdrawn', 'Tërhequr'],
  verified: ['Geprüft', 'Verified', 'Verifikuar'],
  not_verified: ['Nicht bestätigt', 'Not verified', 'Jo e verifikuar'],
  deleted_after_retention: [
    'Nachweis nach Aufbewahrung entfernt',
    'Evidence removed after retention',
    'Dëshmia u hoq pas afatit të ruajtjes',
  ],
  waiting_for_subject: [
    'Rückfrage / fehlende Information',
    'Information requested',
    'Kërkohen informacione',
  ],
  missing_information: [
    'Für die Prüfung fehlen Informationen.',
    'Information is missing for verification.',
    'Mungojnë informacione për verifikim.',
  ],
  resolved: ['Abgeschlossen', 'Resolved', 'Përfunduar'],
  no_violation: ['Kein Regelverstoss', 'No violation', 'Pa shkelje'],
  policy_violation: ['Nicht freigegeben', 'Not approved', 'Nuk u miratua'],
  evidence_not_sufficient: [
    'Nachweis nicht ausreichend',
    'Insufficient evidence',
    'Dëshmi e pamjaftueshme',
  ],
  duplicate_visit: [
    'Doppelter Besuchsnachweis',
    'Duplicate visit evidence',
    'Dëshmi e dyfishtë e vizitës',
  ],
  content_not_publishable: [
    'Inhalt nicht veröffentlichbar',
    'Content cannot be published',
    'Përmbajtja nuk mund të publikohet',
  ],
  other_policy: [
    'Andere begründete Regelentscheidung',
    'Other policy decision',
    'Vendim tjetër sipas rregullave',
  ],
  unavailable: ['Nicht verfügbar', 'Unavailable', 'E padisponueshme'],
  loading: ['Wird geladen …', 'Loading …', 'Duke u ngarkuar …'],
  saving: ['Wird gespeichert …', 'Saving …', 'Duke u ruajtur …'],
  error: [
    'Der Vorgang ist fehlgeschlagen. Deine Eingaben bleiben erhalten. Bitte erneut versuchen.',
    'The operation failed. Your input is preserved. Please try again.',
    'Veprimi dështoi. Të dhënat e tua ruhen. Provo përsëri.',
  ],
  conflict: [
    'Der gespeicherte Stand hat sich geändert oder der Nachweis wurde bereits verwendet. Lade den aktuellen Stand, bevor du erneut speicherst.',
    'The stored state changed or this evidence was already used. Reload the current state before saving again.',
    'Gjendja ka ndryshuar ose dëshmia është përdorur. Rifresko para se të ruash përsëri.',
  ],
  denied: [
    'Für diesen Vorgang fehlt die Berechtigung.',
    'You do not have permission for this action.',
    'Nuk ke leje për këtë veprim.',
  ],
  notFound: [
    'Die Werkstatt oder Bewertung ist nicht mehr verfügbar.',
    'This garage or review is no longer available.',
    'Servisi ose vlerësimi nuk është më i disponueshëm.',
  ],
  invalid: [
    'Bitte prüfe die markierten Angaben und den erforderlichen Nachweis.',
    'Check the marked fields and required evidence.',
    'Kontrollo fushat e shënuara dhe dëshminë e kërkuar.',
  ],
  invalidMonth: [
    'Wähle einen gültigen Besuchsmonat, der nicht in der Zukunft liegt.',
    'Choose a valid visit month that is not in the future.',
    'Zgjidh një muaj të vlefshëm që nuk është në të ardhmen.',
  ],
  selfReview: [
    'Eigene Werkstätten dürfen nicht bewertet werden.',
    'You cannot review your own garage.',
    'Nuk mund të vlerësosh servisin tënd.',
  ],
  adminReview: [
    'Dieses Administratorkonto kann keine Kundenbewertung einreichen.',
    'This administrator account cannot submit a customer review.',
    'Kjo llogari administratori nuk mund të dorëzojë vlerësim klienti.',
  ],
  retry: ['Erneut laden', 'Reload', 'Ringarko'],
  back: ['Zurück', 'Back', 'Kthehu'],
  discard: [
    'Ungespeicherte Eingaben verwerfen?',
    'Discard unsaved changes?',
    'Të hidhen poshtë ndryshimet e paruajtura?',
  ],
  details: ['Details ansehen', 'View details', 'Shiko detajet'],
  empty: [
    'Du hast noch keine Bewertungen eingereicht.',
    'You have not submitted any reviews yet.',
    'Ende nuk ke dorëzuar vlerësime.',
  ],
  previous: ['Vorherige Seite', 'Previous page', 'Faqja e mëparshme'],
  next: ['Nächste Seite', 'Next page', 'Faqja tjetër'],
  openEvidence: ['Privaten Nachweis öffnen', 'Open private evidence', 'Hap dëshminë private'],
  response: ['Werkstattantwort', 'Garage response', 'Përgjigjja e servisit'],
  respond: ['Als Werkstatt antworten', 'Reply as garage', 'Përgjigju si servis'],
  responseEdit: [
    'Werkstattantwort bearbeiten',
    'Edit garage response',
    'Ndrysho përgjigjen e servisit',
  ],
  responseHelp: [
    'Die Antwort wird öffentlich angezeigt. Sterne und Originalbericht des Kunden bleiben unverändert.',
    'Your response is public. The customer’s ratings and original text remain unchanged.',
    'Përgjigjja është publike. Vlerësimi dhe teksti origjinal i klientit nuk ndryshojnë.',
  ],
  update: ['Update zur eigenen Bewertung', 'Update your review', 'Përditëso vlerësimin tënd'],
  updateHelp: [
    'Ein öffentliches Update ergänzt deinen Bericht, ohne die ursprüngliche Bewertung zu überschreiben.',
    'A public update adds to your report without overwriting the original review.',
    'Përditësimi publik plotëson përvojën pa ndryshuar vlerësimin origjinal.',
  ],
  complaint: ['Reklamation', 'Complaint', 'Ankesë'],
  rework: ['Nacharbeit', 'Rework', 'Riparim shtesë'],
  savePublic: ['Öffentlich speichern', 'Save publicly', 'Ruaj publikisht'],
  publicConfirm: [
    'Diesen Text öffentlich veröffentlichen?',
    'Publish this text publicly?',
    'Të publikohet ky tekst?',
  ],
  saved: ['Gespeichert.', 'Saved.', 'U ruajt.'],
  cancel: ['Abbrechen', 'Cancel', 'Anulo'],
};
export function reviewLabel(key: string, language: AppLanguage): string {
  return labels[key]?.[language === 'de' ? 0 : language === 'en' ? 1 : 2] ?? key;
}
