import type { AppLanguage } from './i18n';

export const searchCopy: Readonly<Record<AppLanguage, Readonly<Record<string, string>>>> = {
  de: {
    'search.ui.finishArea': 'Übernimm den Ort oder brich die Bearbeitung ab, bevor du fortfährst.',
    'search.ui.outOfFive': 'von 5',
    'search.ui.reviewCountOne': '{count} Bewertung',
    'search.ui.reviewCount': '{count} Bewertungen',

    'search.ui.selectedAreas': 'Ausgewählte Orte',
    'search.ui.editArea': 'Ort bearbeiten',
    'search.ui.editAreaLabel': '{place}, {radius} km bearbeiten',
    'search.ui.removeAreaLabel': '{place} entfernen',
    'search.ui.confirmArea': 'Übernehmen',
    'search.ui.cancelArea': 'Abbrechen',
    'search.ui.areaError':
      'Wähle einen noch nicht verwendeten Ort und einen Radius von 5 bis 100 km.',

    'favorites.login': 'Anmelden',
    'favorites.dismiss': 'Hinweis schließen',
    'favorites.add': '{garage} als Favorit speichern',
    'favorites.remove': '{garage} aus Favoriten entfernen',
    'favorites.saved': 'Im Benutzerkonto als Favorit gespeichert.',
    'favorites.removed': 'Aus deinen Favoriten entfernt.',
    'favorites.signIn': 'Favorit speichern?',
    'favorites.error': 'Favoriten konnten nicht aktualisiert werden. Bitte versuche es erneut.',

    'search.ui.allLocations': 'Ganz Kosovo',
    'search.ui.chooseLocation': 'Ort auswählen',
    'search.ui.addFirstArea': 'Ort hinzufügen',
    'search.ui.allMakes': 'Alle Marken',

    'search.ui.previousResults': 'Vorherige Ergebnisse – Aktualisierung fehlgeschlagen',
    'search.ui.openFilters': 'Anpassen',
    'search.ui.closeFilters': 'Schließen',
    'search.ui.make': 'Marke',
    'search.ui.allServices': 'Alle Leistungen',

    'search.ui.slogan': 'Mehr als eine Werkstatt. Ein gutes Gefühl.',
    'search.ui.details': 'Details ansehen',
    'search.ui.addArea': 'Weiteren Ort hinzufügen',
    'search.ui.apply': 'Filter anwenden',
    'search.ui.clear': 'Zurücksetzen',
    'search.ui.filter': 'Suchfilter',
    'search.ui.hideMap': 'Kartenbereich schließen',
    'search.ui.mapDisabled': 'Kartenansicht ist derzeit nicht verfügbar',
    'search.ui.mapDisabledBody':
      'Für diese lokale Umgebung ist kein Kartenanbieter konfiguriert. Die Trefferliste und alle Filter bleiben vollständig nutzbar.',
    'search.ui.mapOpen': 'Kartenbereich anzeigen',
    'search.ui.noPhoto': 'Kein veröffentlichtes Foto',
    'search.ui.place': 'Ort oder Region',
    'search.ui.radius': 'Radius in km',
    'search.ui.radiusValue': 'Radius: {radius} km',
    'search.ui.removeArea': 'Ort entfernen',
    'search.ui.resultCount': '{count} passende Werkstätten gefunden',
    'search.ui.sort': 'Sortiert nach',
    'search.ui.sortRating': 'Beste Bewertungsbasis',
    'search.ui.sortRecommended': 'Empfohlen',
    'search.ui.viewList': 'Liste',
    'search.ui.viewMap': 'Karte',
  },
  sq: {
    'search.ui.finishArea': 'Zbato vendin ose anulo ndryshimet para se të vazhdosh.',
    'search.ui.outOfFive': 'nga 5',
    'search.ui.reviewCountOne': '{count} vlerësim',
    'search.ui.reviewCount': '{count} vlerësime',

    'search.ui.selectedAreas': 'Vendet e zgjedhura',
    'search.ui.editArea': 'Ndrysho vendin',
    'search.ui.editAreaLabel': 'Ndrysho {place}, {radius} km',
    'search.ui.removeAreaLabel': 'Hiq {place}',
    'search.ui.confirmArea': 'Zbato',
    'search.ui.cancelArea': 'Anulo',
    'search.ui.areaError': 'Zgjidh një vend tjetër dhe një rreze nga 5 deri në 100 km.',

    'favorites.login': 'Hyr',
    'favorites.dismiss': 'Mbyll njoftimin',
    'favorites.add': 'Ruaj {garage} te të preferuarat',
    'favorites.remove': 'Hiq {garage} nga të preferuarat',
    'favorites.saved': 'U ruajt te të preferuarat në llogarinë tënde.',
    'favorites.removed': 'U hoq nga të preferuarat.',
    'favorites.signIn': 'Ruaj të preferuarat?',
    'favorites.error': 'Të preferuarat nuk u përditësuan. Provo përsëri.',

    'search.ui.allLocations': 'Gjithë Kosova',
    'search.ui.chooseLocation': 'Zgjidh vendin',
    'search.ui.addFirstArea': 'Shto vend',
    'search.ui.allMakes': 'Të gjitha markat',

    'search.ui.previousResults': 'Rezultatet e mëparshme – përditësimi dështoi',
    'search.ui.openFilters': 'Përshtat',
    'search.ui.closeFilters': 'Mbyll',
    'search.ui.make': 'Marka e automjetit',
    'search.ui.allServices': 'Të gjitha shërbimet',

    'search.ui.slogan': 'Më shumë se një servis. Një ndjenjë e mirë.',
    'search.ui.details': 'Shiko detajet',
    'search.ui.addArea': 'Shto një vend tjetër',
    'search.ui.apply': 'Zbato filtrat',
    'search.ui.clear': 'Rivendos',
    'search.ui.filter': 'Filtrat e kërkimit',
    'search.ui.hideMap': 'Mbyll zonën e hartës',
    'search.ui.mapDisabled': 'Pamja e hartës nuk është e disponueshme tani',
    'search.ui.mapDisabledBody':
      'Nuk ka një ofrues harte të konfiguruar për këtë mjedis lokal. Lista e rezultateve dhe filtrat mbeten plotësisht të përdorshëm.',
    'search.ui.mapOpen': 'Shfaq zonën e hartës',
    'search.ui.noPhoto': 'Nuk ka foto të publikuar',
    'search.ui.place': 'Vend ose rajon',
    'search.ui.radius': 'Rrezja në km',
    'search.ui.radiusValue': 'Rrezja: {radius} km',
    'search.ui.removeArea': 'Hiq vendin',
    'search.ui.resultCount': 'U gjetën {count} servise të përshtatshme',
    'search.ui.sort': 'Renditur sipas',
    'search.ui.sortRating': 'Baza më e mirë e vlerësimeve',
    'search.ui.sortRecommended': 'E rekomanduar',
    'search.ui.viewList': 'Listë',
    'search.ui.viewMap': 'Hartë',
  },
  en: {
    'search.ui.finishArea': 'Apply the location or cancel editing before continuing.',
    'search.ui.outOfFive': 'out of 5',
    'search.ui.reviewCountOne': '{count} review',
    'search.ui.reviewCount': '{count} reviews',

    'search.ui.selectedAreas': 'Selected locations',
    'search.ui.editArea': 'Edit location',
    'search.ui.editAreaLabel': 'Edit {place}, {radius} km',
    'search.ui.removeAreaLabel': 'Remove {place}',
    'search.ui.confirmArea': 'Apply',
    'search.ui.cancelArea': 'Cancel',
    'search.ui.areaError': 'Choose an unused location and a radius from 5 to 100 km.',

    'favorites.login': 'Sign in',
    'favorites.dismiss': 'Dismiss notification',
    'favorites.add': 'Save {garage} to favorites',
    'favorites.remove': 'Remove {garage} from favorites',
    'favorites.saved': 'Saved to favorites in your account.',
    'favorites.removed': 'Removed from your favorites.',
    'favorites.signIn': 'Save your favorites?',
    'favorites.error': 'Favorites could not be updated. Please try again.',

    'search.ui.allLocations': 'All of Kosovo',
    'search.ui.chooseLocation': 'Choose a location',
    'search.ui.addFirstArea': 'Add location',
    'search.ui.allMakes': 'All makes',

    'search.ui.previousResults': 'Previous results – refresh failed',
    'search.ui.openFilters': 'Adjust',
    'search.ui.closeFilters': 'Close',
    'search.ui.make': 'Vehicle make',
    'search.ui.allServices': 'All services',

    'search.ui.slogan': 'More than a garage. A good feeling.',
    'search.ui.details': 'View details',
    'search.ui.addArea': 'Add another location',
    'search.ui.apply': 'Apply filters',
    'search.ui.clear': 'Reset',
    'search.ui.filter': 'Search filters',
    'search.ui.hideMap': 'Close map area',
    'search.ui.mapDisabled': 'Map view is not available right now',
    'search.ui.mapDisabledBody':
      'No map provider is configured for this local environment. The results list and all filters remain fully usable.',
    'search.ui.mapOpen': 'Show map area',
    'search.ui.noPhoto': 'No published photo',
    'search.ui.place': 'Location or region',
    'search.ui.radius': 'Radius in km',
    'search.ui.radiusValue': 'Radius: {radius} km',
    'search.ui.removeArea': 'Remove location',
    'search.ui.resultCount': '{count} suitable garages found',
    'search.ui.sort': 'Sort by',
    'search.ui.sortRating': 'Best review basis',
    'search.ui.sortRecommended': 'Recommended',
    'search.ui.viewList': 'List',
    'search.ui.viewMap': 'Map',
  },
};
