import type { AppLanguage } from './i18n';

export const searchCopy: Readonly<Record<AppLanguage, Readonly<Record<string, string>>>> = {
  de: {
    'favorites.login': 'Anmelden',
    'favorites.dismiss': 'Hinweis schließen',
    'favorites.add': '{garage} als Favorit speichern',
    'favorites.remove': '{garage} aus Favoriten entfernen',
    'favorites.saved': 'Im Benutzerkonto als Favorit gespeichert.',
    'favorites.removed': 'Aus deinen Favoriten entfernt.',
    'favorites.signIn': 'Melde dich an, um Favoriten in deinem Konto zu speichern.',
    'favorites.error': 'Favoriten konnten nicht aktualisiert werden. Bitte versuche es erneut.',

    'search.ui.allLocations': 'Ganz Kosovo',
    'search.ui.locationOptional': 'Ort und Radius sind optional.',
    'search.ui.chooseLocation': 'Ort auswählen',
    'search.ui.addFirstArea': 'Ort hinzufügen',
    'search.ui.allMakes': 'Alle Marken',

    'search.ui.previousResults': 'Vorherige Ergebnisse – Aktualisierung fehlgeschlagen',
    'search.ui.openFilters': 'Anpassen',
    'search.ui.closeFilters': 'Schließen',
    'search.ui.make': 'Marke',
    'search.ui.language': 'Sprache',
    'search.ui.allServices': 'Alle Leistungen',
    'search.ui.allLanguages': 'Alle Sprachen',

    'search.ui.slogan': 'Mehr als eine Werkstatt. Ein gutes Gefühl.',
    'search.ui.details': 'Details ansehen',
    'search.ui.addArea': 'Weiteren Ort hinzufügen',
    'search.ui.apply': 'Filter anwenden',
    'search.ui.clear': 'Zurücksetzen',
    'search.ui.filter': 'Suchfilter',
    'search.ui.hideMap': 'Kartenbereich schließen',
    'search.ui.mapDisabled': 'Kartenansicht ist derzeit nicht verfügbar',
    'search.ui.mapDisabledBody':
      'Für diese lokale Umgebung ist kein Kartenanbieter konfiguriert. Die Trefferliste und alle Filter bleiben vollständig nutzbar.',
    'search.ui.mapOpen': 'Kartenbereich anzeigen',
    'search.ui.noPhoto': 'Kein veröffentlichtes Foto',
    'search.ui.place': 'Ort oder Region',
    'search.ui.radius': 'Radius in km',
    'search.ui.radiusValue': 'Radius: {radius} km',
    'search.ui.removeArea': 'Ort entfernen',
    'search.ui.resultCount': '{count} passende Werkstätten gefunden',
    'search.ui.sort': 'Sortiert nach',
    'search.ui.sortRating': 'Beste Bewertungsbasis',
    'search.ui.sortRecommended': 'Empfohlen',
    'search.ui.viewList': 'Liste',
    'search.ui.viewMap': 'Karte',
  },
  sq: {
    'favorites.login': 'Hyr',
    'favorites.dismiss': 'Mbyll njoftimin',
    'favorites.add': 'Ruaj {garage} te të preferuarat',
    'favorites.remove': 'Hiq {garage} nga të preferuarat',
    'favorites.saved': 'U ruajt te të preferuarat në llogarinë tënde.',
    'favorites.removed': 'U hoq nga të preferuarat.',
    'favorites.signIn': 'Hyr për të ruajtur të preferuarat në llogarinë tënde.',
    'favorites.error': 'Të preferuarat nuk u përditësuan. Provo përsëri.',

    'search.ui.allLocations': 'Gjithë Kosova',
    'search.ui.locationOptional': 'Vendi dhe rrezja janë opsionale.',
    'search.ui.chooseLocation': 'Zgjidh vendin',
    'search.ui.addFirstArea': 'Shto vend',
    'search.ui.allMakes': 'Të gjitha markat',

    'search.ui.previousResults': 'Rezultatet e mëparshme – përditësimi dështoi',
    'search.ui.openFilters': 'Përshtat',
    'search.ui.closeFilters': 'Mbyll',
    'search.ui.make': 'Marka e automjetit',
    'search.ui.language': 'Gjuha',
    'search.ui.allServices': 'Të gjitha shërbimet',
    'search.ui.allLanguages': 'Të gjitha gjuhët',

    'search.ui.slogan': 'Më shumë se një servis. Një ndjenjë e mirë.',
    'search.ui.details': 'Shiko detajet',
    'search.ui.addArea': 'Shto një vend tjetër',
    'search.ui.apply': 'Zbato filtrat',
    'search.ui.clear': 'Rivendos',
    'search.ui.filter': 'Filtrat e kërkimit',
    'search.ui.hideMap': 'Mbyll zonën e hartës',
    'search.ui.mapDisabled': 'Pamja e hartës nuk është e disponueshme tani',
    'search.ui.mapDisabledBody':
      'Nuk ka një ofrues harte të konfiguruar për këtë mjedis lokal. Lista e rezultateve dhe filtrat mbeten plotësisht të përdorshëm.',
    'search.ui.mapOpen': 'Shfaq zonën e hartës',
    'search.ui.noPhoto': 'Nuk ka foto të publikuar',
    'search.ui.place': 'Vend ose rajon',
    'search.ui.radius': 'Rrezja në km',
    'search.ui.radiusValue': 'Rrezja: {radius} km',
    'search.ui.removeArea': 'Hiq vendin',
    'search.ui.resultCount': 'U gjetën {count} servise të përshtatshme',
    'search.ui.sort': 'Renditur sipas',
    'search.ui.sortRating': 'Baza më e mirë e vlerësimeve',
    'search.ui.sortRecommended': 'E rekomanduar',
    'search.ui.viewList': 'Listë',
    'search.ui.viewMap': 'Hartë',
  },
  en: {
    'favorites.login': 'Sign in',
    'favorites.dismiss': 'Dismiss notification',
    'favorites.add': 'Save {garage} to favorites',
    'favorites.remove': 'Remove {garage} from favorites',
    'favorites.saved': 'Saved to favorites in your account.',
    'favorites.removed': 'Removed from your favorites.',
    'favorites.signIn': 'Sign in to save favorites in your account.',
    'favorites.error': 'Favorites could not be updated. Please try again.',

    'search.ui.allLocations': 'All of Kosovo',
    'search.ui.locationOptional': 'Location and radius are optional.',
    'search.ui.chooseLocation': 'Choose a location',
    'search.ui.addFirstArea': 'Add location',
    'search.ui.allMakes': 'All makes',

    'search.ui.previousResults': 'Previous results – refresh failed',
    'search.ui.openFilters': 'Adjust',
    'search.ui.closeFilters': 'Close',
    'search.ui.make': 'Vehicle make',
    'search.ui.language': 'Language',
    'search.ui.allServices': 'All services',
    'search.ui.allLanguages': 'All languages',

    'search.ui.slogan': 'More than a garage. A good feeling.',
    'search.ui.details': 'View details',
    'search.ui.addArea': 'Add another location',
    'search.ui.apply': 'Apply filters',
    'search.ui.clear': 'Reset',
    'search.ui.filter': 'Search filters',
    'search.ui.hideMap': 'Close map area',
    'search.ui.mapDisabled': 'Map view is not available right now',
    'search.ui.mapDisabledBody':
      'No map provider is configured for this local environment. The results list and all filters remain fully usable.',
    'search.ui.mapOpen': 'Show map area',
    'search.ui.noPhoto': 'No published photo',
    'search.ui.place': 'Location or region',
    'search.ui.radius': 'Radius in km',
    'search.ui.radiusValue': 'Radius: {radius} km',
    'search.ui.removeArea': 'Remove location',
    'search.ui.resultCount': '{count} suitable garages found',
    'search.ui.sort': 'Sort by',
    'search.ui.sortRating': 'Best review basis',
    'search.ui.sortRecommended': 'Recommended',
    'search.ui.viewList': 'List',
    'search.ui.viewMap': 'Map',
  },
};
