import type { AppLanguage } from './i18n';

export const searchCopy: Readonly<Record<AppLanguage, Readonly<Record<string, string>>>> = {
  de: {
    'search.ui.details': 'Details ansehen',
    'search.ui.heroIntro':
      'Vergleiche geprüfte Werkstätten in deiner Nähe und finde den passenden Service für dein Fahrzeug – schnell, transparent und nachvollziehbar.',
    'search.ui.addArea': 'Weiteren Ort hinzufügen',
    'search.ui.apply': 'Filter anwenden',
    'search.ui.clear': 'Zurücksetzen',
    'search.ui.filter': 'Suchfilter',
    'search.ui.hideMap': 'Kartenbereich schließen',
    'search.ui.mapDisabled': 'Kartenansicht ist derzeit nicht verfügbar',
    'search.ui.mapDisabledBody':
      'Für diese lokale Umgebung ist kein Kartenanbieter konfiguriert. Die Trefferliste und alle Filter bleiben vollständig nutzbar.',
    'search.ui.mapOpen': 'Kartenbereich anzeigen',
    'search.ui.noPhoto': 'Kein veröffentlichtes Foto',
    'search.ui.place': 'Ort oder Region',
    'search.ui.radius': 'Radius in km',
    'search.ui.removeArea': 'Ort entfernen',
    'search.ui.resultCount': '{count} passende Werkstätten gefunden',
    'search.ui.sort': 'Sortiert nach',
    'search.ui.sortRating': 'Beste Bewertungsbasis',
    'search.ui.sortRecommended': 'Empfohlen',
    'search.ui.viewList': 'Liste',
    'search.ui.viewMap': 'Karte',
  },
  sq: {
    'search.ui.details': 'Shiko detajet',
    'search.ui.heroIntro':
      'Krahaso servise të kontrolluara pranë teje dhe gjej shërbimin e përshtatshëm për automjetin tënd – shpejt, qartë dhe në mënyrë të kuptueshme.',
    'search.ui.addArea': 'Shto një vend tjetër',
    'search.ui.apply': 'Zbato filtrat',
    'search.ui.clear': 'Rivendos',
    'search.ui.filter': 'Filtrat e kërkimit',
    'search.ui.hideMap': 'Mbyll zonën e hartës',
    'search.ui.mapDisabled': 'Pamja e hartës nuk është e disponueshme tani',
    'search.ui.mapDisabledBody':
      'Nuk ka një ofrues harte të konfiguruar për këtë mjedis lokal. Lista e rezultateve dhe filtrat mbeten plotësisht të përdorshëm.',
    'search.ui.mapOpen': 'Shfaq zonën e hartës',
    'search.ui.noPhoto': 'Nuk ka foto të publikuar',
    'search.ui.place': 'Vend ose rajon',
    'search.ui.radius': 'Rrezja në km',
    'search.ui.removeArea': 'Hiq vendin',
    'search.ui.resultCount': 'U gjetën {count} servise të përshtatshme',
    'search.ui.sort': 'Renditur sipas',
    'search.ui.sortRating': 'Baza më e mirë e vlerësimeve',
    'search.ui.sortRecommended': 'E rekomanduar',
    'search.ui.viewList': 'Listë',
    'search.ui.viewMap': 'Hartë',
  },
  en: {
    'search.ui.details': 'View details',
    'search.ui.heroIntro':
      'Compare checked garages near you and find the suitable service for your vehicle — quickly, transparently and with clear reasons.',
    'search.ui.addArea': 'Add another location',
    'search.ui.apply': 'Apply filters',
    'search.ui.clear': 'Reset',
    'search.ui.filter': 'Search filters',
    'search.ui.hideMap': 'Close map area',
    'search.ui.mapDisabled': 'Map view is not available right now',
    'search.ui.mapDisabledBody':
      'No map provider is configured for this local environment. The results list and all filters remain fully usable.',
    'search.ui.mapOpen': 'Show map area',
    'search.ui.noPhoto': 'No published photo',
    'search.ui.place': 'Location or region',
    'search.ui.radius': 'Radius in km',
    'search.ui.removeArea': 'Remove location',
    'search.ui.resultCount': '{count} suitable garages found',
    'search.ui.sort': 'Sort by',
    'search.ui.sortRating': 'Best review basis',
    'search.ui.sortRecommended': 'Recommended',
    'search.ui.viewList': 'List',
    'search.ui.viewMap': 'Map',
  },
};
