import type { AppLanguage } from './i18n';
const de = {
  admin: 'Administration',
  moderation: 'Moderation',
  intro: 'Fälle zuweisen, prüfen und zur zuständigen Person weitergeben.',
  adminIntro:
    'Gesamte Fallübersicht und Zuweisung. Weitere Verwaltungsbereiche werden separat ergänzt.',
  ownIntro: 'Nur ausdrücklich zugewiesene Fälle sind hier zugänglich.',
  cases: 'Fälle',
  empty: 'Keine passenden Fälle vorhanden.',
  loading: 'Arbeitsbereich wird geladen …',
  guest: 'Bitte mit deinem berechtigten Konto anmelden.',
  login: 'Anmelden',
  denied: 'Für diesen Arbeitsbereich fehlt die Berechtigung.',
  error: 'Der Arbeitsbereich ist gerade nicht verfügbar. Bitte erneut versuchen.',
  conflict:
    'Der Fall wurde inzwischen geändert. Bitte neu laden und die aktuelle Entscheidung prüfen.',
  unavailable: 'Der Fall ist nicht mehr zugänglich. Möglicherweise wurde die Zuweisung geändert.',
  retry: 'Erneut laden',
  all: 'Alle',
  open: 'Fall ansehen',
  back: 'Zur Fallliste',
  previous: 'Vorherige',
  next: 'Weitere Fälle',
  assigned: 'Zugewiesen',
  unassigned: 'Nicht zugewiesen',
  created: 'Eingegangen',
  status: 'Status',
  priority: 'Priorität',
  high: 'Dringend',
  normal: 'Normal',
  kind: 'Fallart',
  report: 'Inhaltsmeldung',
  review_submission: 'Besuchsnachweis prüfen',
  garage_submission: 'Werkstattaufnahme',
  data_deletion: 'Löschvorgang',
  submitted: 'Eingereicht',
  waiting_for_subject: 'Rückfrage offen',
  resolved: 'Abgeschlossen',
  rejected: 'Abgelehnt',
  assign: 'Zuweisen',
  moderator: 'Moderator',
  choose: 'Bitte auswählen',
  noModerators:
    'Keine verifizierten Moderatoren verfügbar. Das Testkonto muss sich zunächst regulär anmelden.',
  reason: 'Grund',
  escalate: 'Zur Adminprüfung geben',
  requires_admin: 'Administrative Entscheidung erforderlich',
  conflict_of_interest: 'Eigene Beteiligung / Interessenkonflikt',
  missing_information: 'Informationen fehlen',
  escalation: 'Adminprüfung erforderlich',
  escalationConfirm:
    'Diesen Fall an die Administration zurückgeben? Deine Zuweisung wird aufgehoben.',
  success: 'Änderung gespeichert.',
  history: 'Fallverlauf',
  noHistory: 'Noch keine Ereignisse.',
  appeals: 'Widersprüche',
  interest:
    'Du bist an diesem Fall beteiligt. Keine Selbstentscheidung; an eine andere berechtigte Person übergeben.',
  reportDetails: 'Meldung',
  evidence: 'Privaten Nachweis öffnen',
  evidenceUnavailable: 'Der Nachweis ist nicht verfügbar.',
  visit: 'Besuchsmonat',
  service: 'Arbeit / Leistung',
  evidenceStatus: 'Nachweisstatus',
  reviewStatus: 'Bewertungsstatus',
  refreshHint: 'Zuweisungen und Entscheidungen werden vor jeder Aktion erneut geprüft.',
};
type Copy = typeof de;
const en: Copy = {
  admin: 'Administration',
  moderation: 'Moderation',
  intro: 'Assign, inspect and hand over cases to the responsible person.',
  adminIntro:
    'All cases and assignments. Additional administration areas are implemented separately.',
  ownIntro: 'Only explicitly assigned cases are accessible here.',
  cases: 'Cases',
  empty: 'No matching cases.',
  loading: 'Loading workspace …',
  guest: 'Please sign in with your authorized account.',
  login: 'Sign in',
  denied: 'You do not have permission to access this workspace.',
  error: 'The workspace is unavailable. Please try again.',
  conflict: 'This case has changed. Reload and check the current decision.',
  unavailable: 'This case is no longer accessible. Its assignment may have changed.',
  retry: 'Reload',
  all: 'All',
  open: 'View case',
  back: 'Back to cases',
  previous: 'Previous',
  next: 'More cases',
  assigned: 'Assigned',
  unassigned: 'Unassigned',
  created: 'Received',
  status: 'Status',
  priority: 'Priority',
  high: 'Urgent',
  normal: 'Normal',
  kind: 'Case type',
  report: 'Content report',
  review_submission: 'Visit evidence review',
  garage_submission: 'Garage registration',
  data_deletion: 'Data deletion',
  submitted: 'Submitted',
  waiting_for_subject: 'Awaiting information',
  resolved: 'Resolved',
  rejected: 'Rejected',
  assign: 'Assign',
  moderator: 'Moderator',
  choose: 'Please choose',
  noModerators: 'No verified moderators available. The test account must first sign in normally.',
  reason: 'Reason',
  escalate: 'Refer to administration',
  requires_admin: 'Administrative decision required',
  conflict_of_interest: 'Personal involvement / conflict of interest',
  missing_information: 'Missing information',
  escalation: 'Administration review required',
  escalationConfirm: 'Refer this case to administration? Your assignment will be removed.',
  success: 'Change saved.',
  history: 'Case history',
  noHistory: 'No events yet.',
  appeals: 'Appeals',
  interest:
    'You are involved in this case. Do not decide it yourself; hand it over to another authorized person.',
  reportDetails: 'Report',
  evidence: 'Open private evidence',
  evidenceUnavailable: 'Evidence is unavailable.',
  visit: 'Visit month',
  service: 'Work / service',
  evidenceStatus: 'Evidence status',
  reviewStatus: 'Review status',
  refreshHint: 'Assignments and permissions are checked again before every action.',
};
const sq: Copy = {
  admin: 'Administrimi',
  moderation: 'Moderimi',
  intro: 'Caktoni, shqyrtoni dhe përcillni rastet te personi përgjegjës.',
  adminIntro: 'Të gjitha rastet dhe caktimet. Fushat e tjera të administrimit shtohen veçmas.',
  ownIntro: 'Këtu shfaqen vetëm rastet që ju janë caktuar.',
  cases: 'Rastet',
  empty: 'Nuk ka raste që përputhen.',
  loading: 'Duke ngarkuar hapësirën e punës …',
  guest: 'Hyni me llogarinë tuaj të autorizuar.',
  login: 'Hyr',
  denied: 'Nuk keni leje për këtë hapësirë pune.',
  error: 'Hapësira e punës nuk është e disponueshme. Provoni përsëri.',
  conflict: 'Rasti ka ndryshuar. Ringarkoni dhe kontrolloni vendimin aktual.',
  unavailable: 'Rasti nuk është më i qasshëm. Caktimi mund të ketë ndryshuar.',
  retry: 'Ringarko',
  all: 'Të gjitha',
  open: 'Shiko rastin',
  back: 'Kthehu te rastet',
  previous: 'Të mëparshmet',
  next: 'Raste të tjera',
  assigned: 'I caktuar',
  unassigned: 'I pacaktuar',
  created: 'Pranuar',
  status: 'Statusi',
  priority: 'Përparësia',
  high: 'Urgjent',
  normal: 'Normal',
  kind: 'Lloji i rastit',
  report: 'Raportim përmbajtjeje',
  review_submission: 'Kontrolli i dëshmisë së vizitës',
  garage_submission: 'Regjistrimi i servisit',
  data_deletion: 'Fshirja e të dhënave',
  submitted: 'I dorëzuar',
  waiting_for_subject: 'Në pritje të informacionit',
  resolved: 'I përfunduar',
  rejected: 'I refuzuar',
  assign: 'Cakto',
  moderator: 'Moderatori',
  choose: 'Zgjidhni',
  noModerators:
    'Nuk ka moderatorë të verifikuar. Llogaria e testimit duhet së pari të hyjë normalisht.',
  reason: 'Arsyeja',
  escalate: 'Përcille për shqyrtim administrativ',
  requires_admin: 'Nevojitet vendim administrativ',
  conflict_of_interest: 'Përfshirje personale / konflikt interesi',
  missing_information: 'Mungon informacioni',
  escalation: 'Nevojitet shqyrtim administrativ',
  escalationConfirm: 'Ta përcillni rastin te administrimi? Caktimi juaj do të hiqet.',
  success: 'Ndryshimi u ruajt.',
  history: 'Historiku i rastit',
  noHistory: 'Ende nuk ka ngjarje.',
  appeals: 'Ankesat',
  interest:
    'Jeni të përfshirë në këtë rast. Mos vendosni vetë; përcilleni te një person tjetër i autorizuar.',
  reportDetails: 'Raportimi',
  evidence: 'Hap dëshminë private',
  evidenceUnavailable: 'Dëshmia nuk është e disponueshme.',
  visit: 'Muaji i vizitës',
  service: 'Puna / shërbimi',
  evidenceStatus: 'Statusi i dëshmisë',
  reviewStatus: 'Statusi i vlerësimit',
  refreshHint: 'Caktimet dhe lejet kontrollohen përsëri para çdo veprimi.',
};
export function staffCopy(language: AppLanguage): Copy {
  return language === 'sq' ? sq : language === 'en' ? en : de;
}

const extraLabels: Readonly<Record<string, readonly [string, string, string]>> = {
  workspace: ['Arbeitsbereiche', 'Workspaces', 'Hapësirat e punës'],
  under_review: ['In Prüfung', 'Under review', 'Në shqyrtim'],
  published: ['Veröffentlicht', 'Published', 'I publikuar'],
  temporarily_hidden: ['Vorläufig ausgeblendet', 'Temporarily hidden', 'Përkohësisht i fshehur'],
  verified: ['Geprüft', 'Verified', 'I verifikuar'],
  not_verified: ['Nicht bestätigt', 'Not verified', 'I paverifikuar'],
  deleted_after_retention: [
    'Nach Aufbewahrungsfrist gelöscht',
    'Deleted after retention',
    'I fshirë pas afatit të ruajtjes',
  ],
  personal_data: ['Personenbezogene Daten', 'Personal data', 'Të dhëna personale'],
  impersonation: ['Identitätstäuschung', 'Impersonation', 'Imitim identiteti'],
  spam_or_deception: ['Spam / Täuschung', 'Spam / deception', 'Postë e padëshiruar / mashtrim'],
  unsafe_content: ['Gefährdende Inhalte', 'Unsafe content', 'Përmbajtje e pasigurt'],
  other_policy_concern: [
    'Sonstiger Regelverstoß',
    'Other policy concern',
    'Shkelje tjetër e rregullave',
  ],
  'demo-case-prepared': [
    'Fiktiver Ausgangsfall vorbereitet',
    'Fictional starting case prepared',
    'Rasti fillestar fiktiv u përgatit',
  ],
  'staff-case-assigned': ['Fall zugewiesen', 'Case assigned', 'Rasti u caktua'],
  'staff-case-escalated-requires_admin': [
    'Zur Adminprüfung gegeben',
    'Referred to administration',
    'U përcoll për shqyrtim administrativ',
  ],
  'staff-case-escalated-conflict_of_interest': [
    'Wegen Interessenkonflikt abgegeben',
    'Handed over due to conflict of interest',
    'U përcoll për shkak të konfliktit të interesit',
  ],
  'staff-case-escalated-missing_information': [
    'Wegen fehlender Informationen abgegeben',
    'Handed over due to missing information',
    'U përcoll për mungesë informacioni',
  ],
  'review-submitted': ['Bewertung eingereicht', 'Review submitted', 'Vlerësimi u dorëzua'],
  'review-assigned': [
    'Bewertungsprüfung zugewiesen',
    'Review assigned',
    'Shqyrtimi i vlerësimit u caktua',
  ],
  'review-published': ['Bewertung veröffentlicht', 'Review published', 'Vlerësimi u publikua'],
  'review-rejected': ['Bewertung abgelehnt', 'Review rejected', 'Vlerësimi u refuzua'],
};
export function staffLabel(value: string, language: AppLanguage): string {
  const extra = extraLabels[value];
  if (extra) return extra[language === 'de' ? 0 : language === 'en' ? 1 : 2];
  const copy = staffCopy(language);
  return (copy as unknown as Record<string, string>)[value] ?? value;
}
