import type { AppLanguage } from './i18n';
const de = {
  admin: 'Administration',
  moderation: 'Moderation',
  intro: 'Fälle zuweisen, prüfen und zur zuständigen Person weitergeben.',
  adminIntro: 'Handlungsbereite Aufgaben prüfen, zuweisen und abschliessen.',
  ownIntro: 'Nur ausdrücklich zugewiesene Fälle sind hier zugänglich.',
  cases: 'Fälle',
  publicSite: 'Öffentliche Website ansehen',
  legal: 'Datenschutz',
  taskQueue: 'Alle Fälle anzeigen',
  allCases: 'Nur Aufgaben anzeigen',
  moreFilters: 'Weitere Filter',
  reset: 'Zurücksetzen',
  myCases: 'Meine Fälle',
  todo: 'Zu bearbeiten',
  waiting: 'Wartet',
  done: 'Erledigt',
  empty: 'Keine passenden Fälle vorhanden.',
  loading: 'Arbeitsbereich wird geladen …',
  guest: 'Bitte mit deinem berechtigten Konto anmelden.',
  login: 'Anmelden',
  denied: 'Für diesen Arbeitsbereich fehlt die Berechtigung.',
  error: 'Der Arbeitsbereich ist gerade nicht verfügbar. Bitte erneut versuchen.',
  conflict:
    'Der Fall wurde inzwischen geändert. Bitte neu laden und die aktuelle Entscheidung prüfen.',
  unavailable: 'Der Fall ist nicht mehr zugänglich. Möglicherweise wurde die Zuweisung geändert.',
  retry: 'Erneut laden',
  all: 'Alle',
  open: 'Fall ansehen',
  back: 'Zur Fallliste',
  previous: 'Vorherige',
  next: 'Weitere Fälle',
  assigned: 'Zugewiesen',
  unassigned: 'Nicht zugewiesen',
  created: 'Eingegangen',
  status: 'Status',
  priority: 'Priorität',
  high: 'Dringend',
  normal: 'Normal',
  kind: 'Fallart',
  report: 'Inhaltsmeldung',
  review_submission: 'Besuchsnachweis prüfen',
  garage_submission: 'Werkstattaufnahme',
  data_deletion: 'Löschvorgang',
  submitted: 'Eingereicht',
  waiting_for_subject: 'Rückfrage offen',
  resolved: 'Abgeschlossen',
  rejected: 'Abgelehnt',
  assign: 'Zuweisen',
  moderator: 'Moderator',
  choose: 'Bitte auswählen',
  noModerators:
    'Keine verifizierten Moderatoren verfügbar. Das Testkonto muss sich zunächst regulär anmelden.',
  reason: 'Grund',
  escalate: 'Zur Adminprüfung geben',
  requires_admin: 'Administrative Entscheidung erforderlich',
  conflict_of_interest: 'Eigene Beteiligung / Interessenkonflikt',
  missing_information: 'Informationen fehlen',
  escalation: 'Adminprüfung erforderlich',
  escalationConfirm:
    'Diesen Fall an die Administration zurückgeben? Deine Zuweisung wird aufgehoben.',
  success: 'Änderung gespeichert.',
  history: 'Fallverlauf',
  noHistory: 'Noch keine Ereignisse.',
  appeals: 'Widersprüche',
  interest:
    'Du bist an diesem Fall beteiligt. Keine Selbstentscheidung; an eine andere berechtigte Person übergeben.',
  reportDetails: 'Meldung',
  evidence: 'Privaten Nachweis öffnen',
  evidenceUnavailable:
    'Der Nachweis fehlt oder wurde entzogen. Veröffentlichung ist gesperrt; ablehnen oder eine Rückfrage vermerken.',
  visit: 'Besuchsmonat',
  service: 'Arbeit / Leistung',
  evidenceStatus: 'Nachweisstatus',
  reviewStatus: 'Bewertungsstatus',
  refreshHint: 'Zuweisungen und Entscheidungen werden vor jeder Aktion erneut geprüft.',
};
type Copy = typeof de;
const en: Copy = {
  admin: 'Administration',
  moderation: 'Moderation',
  intro: 'Assign, inspect and hand over cases to the responsible person.',
  adminIntro: 'Review, assign and complete actionable work.',
  ownIntro: 'Only explicitly assigned cases are accessible here.',
  cases: 'Cases',
  publicSite: 'View public site',
  legal: 'Privacy',
  taskQueue: 'Show all cases',
  allCases: 'Show tasks only',
  moreFilters: 'More filters',
  reset: 'Reset',
  myCases: 'My cases',
  todo: 'To do',
  waiting: 'Waiting',
  done: 'Done',
  empty: 'No matching cases.',
  loading: 'Loading workspace …',
  guest: 'Please sign in with your authorized account.',
  login: 'Sign in',
  denied: 'You do not have permission to access this workspace.',
  error: 'The workspace is unavailable. Please try again.',
  conflict: 'This case has changed. Reload and check the current decision.',
  unavailable: 'This case is no longer accessible. Its assignment may have changed.',
  retry: 'Reload',
  all: 'All',
  open: 'View case',
  back: 'Back to cases',
  previous: 'Previous',
  next: 'More cases',
  assigned: 'Assigned',
  unassigned: 'Unassigned',
  created: 'Received',
  status: 'Status',
  priority: 'Priority',
  high: 'Urgent',
  normal: 'Normal',
  kind: 'Case type',
  report: 'Content report',
  review_submission: 'Visit evidence review',
  garage_submission: 'Garage registration',
  data_deletion: 'Data deletion',
  submitted: 'Submitted',
  waiting_for_subject: 'Awaiting information',
  resolved: 'Resolved',
  rejected: 'Rejected',
  assign: 'Assign',
  moderator: 'Moderator',
  choose: 'Please choose',
  noModerators: 'No verified moderators available. The test account must first sign in normally.',
  reason: 'Reason',
  escalate: 'Refer to administration',
  requires_admin: 'Administrative decision required',
  conflict_of_interest: 'Personal involvement / conflict of interest',
  missing_information: 'Missing information',
  escalation: 'Administration review required',
  escalationConfirm: 'Refer this case to administration? Your assignment will be removed.',
  success: 'Change saved.',
  history: 'Case history',
  noHistory: 'No events yet.',
  appeals: 'Appeals',
  interest:
    'You are involved in this case. Do not decide it yourself; hand it over to another authorized person.',
  reportDetails: 'Report',
  evidence: 'Open private evidence',
  evidenceUnavailable:
    'Evidence is missing or withdrawn. Publishing is blocked; reject it or record an information request.',
  visit: 'Visit month',
  service: 'Work / service',
  evidenceStatus: 'Evidence status',
  reviewStatus: 'Review status',
  refreshHint: 'Assignments and permissions are checked again before every action.',
};
const sq: Copy = {
  admin: 'Administrimi',
  moderation: 'Moderimi',
  intro: 'Caktoni, shqyrtoni dhe përcillni rastet te personi përgjegjës.',
  adminIntro: 'Shqyrtoni, caktoni dhe përfundoni punën që kërkon veprim.',
  ownIntro: 'Këtu shfaqen vetëm rastet që ju janë caktuar.',
  cases: 'Rastet',
  publicSite: 'Shiko faqen publike',
  legal: 'Privatësia',
  taskQueue: 'Shfaq të gjitha rastet',
  allCases: 'Shfaq vetëm detyrat',
  moreFilters: 'Më shumë filtra',
  reset: 'Rivendos',
  myCases: 'Rastet e mia',
  todo: 'Për veprim',
  waiting: 'Në pritje',
  done: 'Përfunduar',
  empty: 'Nuk ka raste që përputhen.',
  loading: 'Duke ngarkuar hapësirën e punës …',
  guest: 'Hyni me llogarinë tuaj të autorizuar.',
  login: 'Hyr',
  denied: 'Nuk keni leje për këtë hapësirë pune.',
  error: 'Hapësira e punës nuk është e disponueshme. Provoni përsëri.',
  conflict: 'Rasti ka ndryshuar. Ringarkoni dhe kontrolloni vendimin aktual.',
  unavailable: 'Rasti nuk është më i qasshëm. Caktimi mund të ketë ndryshuar.',
  retry: 'Ringarko',
  all: 'Të gjitha',
  open: 'Shiko rastin',
  back: 'Kthehu te rastet',
  previous: 'Të mëparshmet',
  next: 'Raste të tjera',
  assigned: 'I caktuar',
  unassigned: 'I pacaktuar',
  created: 'Pranuar',
  status: 'Statusi',
  priority: 'Përparësia',
  high: 'Urgjent',
  normal: 'Normal',
  kind: 'Lloji i rastit',
  report: 'Raportim përmbajtjeje',
  review_submission: 'Kontrolli i dëshmisë së vizitës',
  garage_submission: 'Regjistrimi i servisit',
  data_deletion: 'Fshirja e të dhënave',
  submitted: 'I dorëzuar',
  waiting_for_subject: 'Në pritje të informacionit',
  resolved: 'I përfunduar',
  rejected: 'I refuzuar',
  assign: 'Cakto',
  moderator: 'Moderatori',
  choose: 'Zgjidhni',
  noModerators:
    'Nuk ka moderatorë të verifikuar. Llogaria e testimit duhet së pari të hyjë normalisht.',
  reason: 'Arsyeja',
  escalate: 'Përcille për shqyrtim administrativ',
  requires_admin: 'Nevojitet vendim administrativ',
  conflict_of_interest: 'Përfshirje personale / konflikt interesi',
  missing_information: 'Mungon informacioni',
  escalation: 'Nevojitet shqyrtim administrativ',
  escalationConfirm: 'Ta përcillni rastin te administrimi? Caktimi juaj do të hiqet.',
  success: 'Ndryshimi u ruajt.',
  history: 'Historiku i rastit',
  noHistory: 'Ende nuk ka ngjarje.',
  appeals: 'Ankesat',
  interest:
    'Jeni të përfshirë në këtë rast. Mos vendosni vetë; përcilleni te një person tjetër i autorizuar.',
  reportDetails: 'Raportimi',
  evidence: 'Hap dëshminë private',
  evidenceUnavailable:
    'Dëshmia mungon ose është tërhequr. Publikimi është i bllokuar; refuzoje ose shëno një kërkesë për informacion.',
  visit: 'Muaji i vizitës',
  service: 'Puna / shërbimi',
  evidenceStatus: 'Statusi i dëshmisë',
  reviewStatus: 'Statusi i vlerësimit',
  refreshHint: 'Caktimet dhe lejet kontrollohen përsëri para çdo veprimi.',
};
export function staffCopy(language: AppLanguage): Copy {
  return language === 'sq' ? sq : language === 'en' ? en : de;
}

const extraLabels: Readonly<Record<string, readonly [string, string, string]>> = {
  profilePhoto: [
    'Öffentliches Demo-Profilfoto',
    'Public demo profile photo',
    'Foto publike e profilit demo',
  ],
  mediaBoundary: [
    'Nicht verfügbare Bilder oder einzelne unzulässige Antworten zur Adminprüfung geben. Keine unbeteiligte Bewertung entfernen.',
    'Refer unavailable images or individual inappropriate responses to administration. Do not remove an unrelated review.',
    'Përcillni imazhet e padisponueshme ose përgjigjet e papërshtatshme për shqyrtim administrativ. Mos hiqni një vlerësim të palidhur.',
  ],
  decision: ['Entscheidung', 'Decision', 'Vendimi'],
  action: ['Aktion', 'Action', 'Veprimi'],
  saveDecision: ['Entscheidung speichern', 'Save decision', 'Ruaj vendimin'],
  checklist: ['Nachweis prüfen', 'Check evidence', 'Kontrollo dëshminë'],
  garageMatches: [
    'Nachweis passt zur Werkstatt',
    'Evidence matches the garage',
    'Dëshmia përputhet me servisin',
  ],
  serviceMatches: [
    'Nachweis passt zur Leistung',
    'Evidence matches the service',
    'Dëshmia përputhet me shërbimin',
  ],
  visitMonthMatches: [
    'Nachweis passt zum Besuchsmonat',
    'Evidence matches the visit month',
    'Dëshmia përputhet me muajin e vizitës',
  ],
  publish_review: ['Bewertung veröffentlichen', 'Publish review', 'Publiko vlerësimin'],
  reject_review: ['Bewertung ablehnen', 'Reject review', 'Refuzo vlerësimin'],
  approve: [
    'Meldung ohne Verstoss abschliessen',
    'Close report: no violation',
    'Mbyll raportimin: pa shkelje',
  ],
  request_information: ['Informationen anfordern', 'Request information', 'Kërko informacion'],
  reject: ['Prüfung begründet ablehnen', 'Reject with a reason', 'Refuzo me arsyetim'],
  temporarily_hide: [
    'Inhalt vorläufig ausblenden',
    'Temporarily hide content',
    'Fsheh përkohësisht përmbajtjen',
  ],
  restore: ['Inhalt wiederherstellen', 'Restore content', 'Rikthe përmbajtjen'],
  effect_publish_review: [
    'Die Bewertung wird öffentlich sichtbar. Text und Sterne bleiben unverändert.',
    'The review becomes public. Text and ratings stay unchanged.',
    'Vlerësimi bëhet publik. Teksti dhe yjet mbeten të pandryshuar.',
  ],
  effect_reject_review: [
    'Die Bewertung wird nicht veröffentlicht. Der Autor sieht den Ablehnungsgrund.',
    'The review will not be published. The author can see the rejection reason.',
    'Vlerësimi nuk publikohet. Autori sheh arsyen e refuzimit.',
  ],
  effect_approve: [
    'Die Inhaltsprüfung wird abgeschlossen. Keine Werkstatt-Erstfreigabe oder Änderung von Nachweisprüfungen.',
    'Closes this content check. Does not publish a new garage or verify evidence.',
    'Mbyll kontrollin e përmbajtjes. Nuk publikon servis të ri dhe nuk verifikon dëshmi.',
  ],
  effect_request_information: [
    'Der Fall bleibt mit offener Rückfrage bestehen. Es wird keine E-Mail oder Push-Nachricht versendet.',
    'The case stays open awaiting information. No email or push notification is sent.',
    'Rasti mbetet i hapur në pritje të informacionit. Nuk dërgohet email ose njoftim.',
  ],
  effect_reject: [
    'Die Prüfung wird mit dem gewählten Grund abgeschlossen. Inhalte werden nicht endgültig gelöscht.',
    'The check ends with the selected reason. Content is not permanently deleted.',
    'Kontrolli mbyllet me arsyen e zgjedhur. Përmbajtja nuk fshihet përgjithmonë.',
  ],
  effect_temporarily_hide: [
    'Der Inhalt ist danach öffentlich nicht sichtbar. Original und Nachweise bleiben erhalten.',
    'The content is no longer public. The original and evidence are retained.',
    'Përmbajtja nuk shihet më publikisht. Origjinali dhe dëshmitë ruhen.',
  ],
  effect_restore: [
    'Der zuvor freigegebene Inhalt wird wieder sichtbar. Separate Sperren bleiben wirksam.',
    'Previously approved content becomes public again. Separate restrictions remain effective.',
    'Përmbajtja e miratuar më parë bëhet sërish publike. Kufizimet e veçanta mbeten në fuqi.',
  ],
  duplicate_visit: ['Doppelter Besuchsnachweis', 'Duplicate visit', 'Vizitë e dyfishtë'],
  evidence_not_sufficient: [
    'Nachweis nicht ausreichend',
    'Insufficient evidence',
    'Dëshmi e pamjaftueshme',
  ],
  content_not_publishable: [
    'Inhalt nicht veröffentlichbar',
    'Content cannot be published',
    'Përmbajtja nuk mund të publikohet',
  ],
  other_policy: ['Sonstiger Regelgrund', 'Other policy reason', 'Arsye tjetër e rregullave'],
  policy_violation: ['Regelverstoss', 'Policy violation', 'Shkelje e rregullave'],
  private_data_exposure: [
    'Private Daten offengelegt',
    'Private data exposed',
    'Të dhëna private të zbuluara',
  ],
  abuse: ['Missbrauch', 'Abuse', 'Abuzim'],
  no_violation: ['Kein Verstoss', 'No violation', 'Pa shkelje'],
  noDecision: [
    'Für diesen Fall ist aktuell keine eigene Entscheidung zulässig. Status, Nachweis und Zuständigkeit beachten.',
    'No decision is currently available to you. Check status, evidence and assignment.',
    'Aktualisht nuk ju lejohet vendim për këtë rast. Kontrolloni statusin, dëshminë dhe caktimin.',
  ],
  independentAppeal: [
    'Unabhängige Widerspruchsprüfung: Die vorherige Entscheidung bleibt im Verlauf erhalten.',
    'Independent appeal review: the previous decision stays in the history.',
    'Shqyrtim i pavarur i ankesës: vendimi i mëparshëm ruhet në historik.',
  ],
  originalDecision: ['Ursprüngliche Entscheidung', 'Original decision', 'Vendimi fillestar'],
  appealMessage: ['Widerspruchsnachricht', 'Appeal message', 'Mesazhi i ankesës'],
  outcome_decide: [
    'Entscheidung gespeichert und neu geprüft.',
    'Decision saved and rechecked.',
    'Vendimi u ruajt dhe u kontrollua përsëri.',
  ],
  outcome_assign: [
    'Zuweisung gespeichert; der Fall wurde neu geladen.',
    'Assignment saved; the case was reloaded.',
    'Caktimi u ruajt; rasti u ringarkua.',
  ],
  outcome_escalate: [
    'Fall wurde an die Administration übergeben.',
    'Case was referred to administration.',
    'Rasti u përcoll te administrimi.',
  ],
  garageResponse: ['Werkstattantwort', 'Garage response', 'Përgjigjja e servisit'],
  updates: ['Nachträge des Kunden', 'Customer updates', 'Përditësimet e klientit'],
  workQuality: ['Arbeitsqualität', 'Work quality', 'Cilësia e punës'],
  communication: ['Kommunikation', 'Communication', 'Komunikimi'],
  priceTransparency: ['Preistransparenz', 'Price transparency', 'Transparenca e çmimeve'],
  punctuality: ['Termintreue', 'Punctuality', 'Përpikëria'],
  emptyMine: [
    'Keine passenden zugewiesenen Fälle.',
    'No matching assigned cases.',
    'Nuk ka raste të caktuara që përputhen.',
  ],
  invalidDecision: [
    'Die Entscheidung erfüllt die Voraussetzungen nicht. Eingaben und Nachweis prüfen.',
    'The decision does not meet the requirements. Check inputs and evidence.',
    'Vendimi nuk i plotëson kushtet. Kontrolloni të dhënat dhe dëshminë.',
  ],
  description: ['Profilinhalt', 'Profile content', 'Përmbajtja e profilit'],
  suspended: ['Gesperrt', 'Suspended', 'I pezulluar'],
  pending_review: ['Zur Prüfung eingereicht', 'Pending review', 'Në pritje të shqyrtimit'],
  unavailable: ['Nicht verfügbar', 'Unavailable', 'I padisponueshëm'],
  invoice: ['Rechnung', 'Invoice', 'Faturë'],
  work_order: ['Arbeitsauftrag', 'Work order', 'Urdhër pune'],
  payment_confirmation: ['Zahlungsbestätigung', 'Payment confirmation', 'Konfirmim pagese'],
  garage_confirmation: ['Werkstattbestätigung', 'Garage confirmation', 'Konfirmim nga servisi'],
  other_service_proof: [
    'Anderer Leistungsnachweis',
    'Other service evidence',
    'Dëshmi tjetër shërbimi',
  ],
  complaint: ['Reklamation', 'Complaint', 'Ankesë'],
  rework: ['Nacharbeit', 'Rework', 'Riparim plotësues'],
  'moderation-appeal-submitted': [
    'Widerspruch eingereicht',
    'Appeal submitted',
    'Ankesa u dorëzua',
  ],
  workspace: ['Arbeitsbereiche', 'Workspaces', 'Hapësirat e punës'],
  under_review: ['In Prüfung', 'Under review', 'Në shqyrtim'],
  published: ['Veröffentlicht', 'Published', 'I publikuar'],
  temporarily_hidden: ['Vorläufig ausgeblendet', 'Temporarily hidden', 'Përkohësisht i fshehur'],
  verified: ['Geprüft', 'Verified', 'I verifikuar'],
  not_verified: ['Nicht bestätigt', 'Not verified', 'I paverifikuar'],
  deleted_after_retention: [
    'Nach Aufbewahrungsfrist gelöscht',
    'Deleted after retention',
    'I fshirë pas afatit të ruajtjes',
  ],
  personal_data: ['Personenbezogene Daten', 'Personal data', 'Të dhëna personale'],
  impersonation: ['Identitätstäuschung', 'Impersonation', 'Imitim identiteti'],
  spam_or_deception: ['Spam / Täuschung', 'Spam / deception', 'Postë e padëshiruar / mashtrim'],
  unsafe_content: ['Gefährdende Inhalte', 'Unsafe content', 'Përmbajtje e pasigurt'],
  other_policy_concern: [
    'Sonstiger Regelverstoß',
    'Other policy concern',
    'Shkelje tjetër e rregullave',
  ],
  'demo-case-prepared': [
    'Fiktiver Ausgangsfall vorbereitet',
    'Fictional starting case prepared',
    'Rasti fillestar fiktiv u përgatit',
  ],
  'staff-case-assigned': ['Fall zugewiesen', 'Case assigned', 'Rasti u caktua'],
  'staff-case-escalated-requires_admin': [
    'Zur Adminprüfung gegeben',
    'Referred to administration',
    'U përcoll për shqyrtim administrativ',
  ],
  'staff-case-escalated-conflict_of_interest': [
    'Wegen Interessenkonflikt abgegeben',
    'Handed over due to conflict of interest',
    'U përcoll për shkak të konfliktit të interesit',
  ],
  'staff-case-escalated-missing_information': [
    'Wegen fehlender Informationen abgegeben',
    'Handed over due to missing information',
    'U përcoll për mungesë informacioni',
  ],
  'review-submitted': ['Bewertung eingereicht', 'Review submitted', 'Vlerësimi u dorëzua'],
  'review-assigned': [
    'Bewertungsprüfung zugewiesen',
    'Review assigned',
    'Shqyrtimi i vlerësimit u caktua',
  ],
  'review-published': ['Bewertung veröffentlicht', 'Review published', 'Vlerësimi u publikua'],
  'review-rejected': ['Bewertung abgelehnt', 'Review rejected', 'Vlerësimi u refuzua'],
};
export function staffLabel(value: string, language: AppLanguage): string {
  for (const prefix of ['moderation-case-reason-', 'review-decision-reason-', 'moderation-case-']) {
    if (value.startsWith(prefix)) return staffLabel(value.slice(prefix.length), language);
  }
  const extra = extraLabels[value];
  if (extra) return extra[language === 'de' ? 0 : language === 'en' ? 1 : 2];
  const copy = staffCopy(language);
  return (copy as unknown as Record<string, string>)[value] ?? value;
}
