const demoPlacePoints = {
  'xk-pristina': [42.67272, 21.16688],
  'xk-prizren': [42.21389, 20.73972],
  'xk-peja': [42.65913, 20.28828],
  'xk-gjakova': [42.38028, 20.43083],
  'xk-ferizaj': [42.37056, 21.15528],
  'xk-gjilan': [42.46045, 21.46986],
  'xk-mitrovica': [42.88333, 20.86667],
};

function deterministicDemoPosition(id, placeId) {
  const [latitude, longitude] = demoPlacePoints[placeId];
  const hash = [...id].reduce(
    (value, character) => (value * 31 + character.charCodeAt(0)) >>> 0,
    7,
  );
  // These are deliberately fictional offsets, never a geocoding result or a real business address.
  return {
    latitude: latitude + ((hash % 17) - 8) * 0.0011,
    longitude: longitude + ((Math.floor(hash / 17) % 17) - 8) * 0.0014,
  };
}

function garage(input) {
  return {
    contactPerson: 'Inhaber',
    description: input.scenario,
    publicWhatsapp: true,
    ...input,
    locationPoint: deterministicDemoPosition(input.id, input.placeId),
  };
}

export const demoGarages = [
  garage({
    id: 'demo-prishtina-bremsen',
    contactPerson: 'Arben Krasniqi',
    languages: ['Deutsch', 'Shqip'],
    name: 'Berisha Auto-Service',
    placeId: 'xk-pristina',
    publicPhone: '+383 44 100 101',
    scenario: 'Fachwerkstatt für Bremsen und Bremsbeläge in Prishtina. Alle Fahrzeugmarken.',
    selfReportedSpecializations: ['Bremsen'],
    serviceCategoryIds: ['bremsen'],
    vehicleMakeIds: ['skoda'],
    verification: 'verified',
  }),
  garage({
    id: 'demo-prishtina-reifen',
    contactPerson: 'Besnik Haliti',
    languages: ['Shqip'],
    name: 'Gashi Reifen & Felgen',
    placeId: 'xk-pristina',
    publicPhone: '+383 44 100 102',
    scenario: 'Reifen-Fachbetrieb in Prishtina. Montage, Auswuchten und saisonale Einlagerung.',
    selfReportedSpecializations: ['Reifenwechsel'],
    serviceCategoryIds: ['reifen'],
    vehicleMakeIds: [],
    verification: 'not_checked',
  }),
  garage({
    id: 'demo-ferizaj-bremsen-offen',
    contactPerson: 'Arta Gashi',
    languages: ['Deutsch'],
    name: 'Krasniqi Werkstatt',
    placeId: 'xk-ferizaj',
    publicPhone: '+383 44 100 103',
    scenario: 'Bremsen und Inspektionen für alle Fahrzeugmarken in Ferizaj.',
    selfReportedSpecializations: ['Bremsen', 'Inspektion'],
    serviceCategoryIds: ['bremsen', 'service-inspektion'],
    vehicleMakeIds: [],
    verification: 'verified',
  }),
  garage({
    id: 'demo-prizren-bremsen-vw',
    contactPerson: 'Arben Krasniqi',
    languages: ['Deutsch', 'Shqip'],
    name: 'Haliti Automobile',
    placeId: 'xk-prizren',
    publicPhone: '+383 44 100 104',
    scenario: 'Volkswagen-Spezialist und allgemeiner Bremsendienst in Prizren.',
    selfReportedSpecializations: ['Bremsen'],
    serviceCategoryIds: ['bremsen'],
    vehicleMakeIds: ['volkswagen'],
    verification: 'verified',
  }),
  garage({
    id: 'demo-peja-klima',
    contactPerson: 'Besnik Haliti',
    languages: ['Shqip'],
    name: 'Morina Klimatechnik',
    placeId: 'xk-peja',
    publicPhone: '+383 44 100 105',
    scenario: 'Klimaanlagen-Fachbetrieb für Toyota und alle Marken in Pejë.',
    selfReportedSpecializations: ['Klimaanlage'],
    serviceCategoryIds: ['klima'],
    vehicleMakeIds: ['toyota'],
    verification: 'verified',
  }),
  garage({
    id: 'demo-gjakova-motor-audi',
    contactPerson: 'Arta Gashi',
    languages: ['Deutsch'],
    name: 'Bytyqi Reparaturen',
    placeId: 'xk-gjakova',
    publicPhone: '+383 44 100 106',
    scenario: 'Motor-Instandsetzung und Audi-Spezialbetrieb in Gjakovë.',
    selfReportedSpecializations: ['Motor'],
    serviceCategoryIds: ['motor'],
    vehicleMakeIds: ['audi'],
    verification: 'verified',
  }),
  garage({
    id: 'demo-gjakova-karosserie',
    contactPerson: 'Arben Krasniqi',
    languages: ['Shqip'],
    name: 'Hoti Karosserie',
    placeId: 'xk-gjakova',
    publicPhone: '+383 44 100 107',
    scenario: 'Karosserie- und Lackarbeiten für alle Fahrzeugtypen in Gjakovë.',
    selfReportedSpecializations: ['Karosserie'],
    serviceCategoryIds: ['karosserie'],
    vehicleMakeIds: [],
    verification: 'not_checked',
  }),
  garage({
    id: 'demo-gjilan-elektronik-bmw',
    contactPerson: 'Besnik Haliti',
    languages: ['Deutsch', 'Shqip'],
    name: 'Lleshi Elektronik',
    placeId: 'xk-gjilan',
    publicPhone: '+383 44 100 108',
    scenario: 'Fahrzeugelektronik und BMW-Diagnose in Gjilan.',
    selfReportedSpecializations: ['Diagnose'],
    serviceCategoryIds: ['elektronik-diagnose'],
    vehicleMakeIds: ['bmw'],
    verification: 'verified',
  }),
  garage({
    id: 'demo-gjilan-service-offen',
    contactPerson: 'Arta Gashi',
    languages: ['Shqip'],
    name: 'Auto-Centrum Gjilan',
    placeId: 'xk-gjilan',
    publicPhone: '+383 44 100 109',
    scenario: 'Vollservice und Inspektion für alle Fahrzeugmarken in Gjilan.',
    selfReportedSpecializations: ['Inspektion'],
    serviceCategoryIds: ['service-inspektion'],
    vehicleMakeIds: [],
    verification: 'verified',
  }),
  garage({
    id: 'demo-mitrovica-getriebe-mercedes',
    contactPerson: 'Arben Krasniqi',
    languages: ['Deutsch'],
    name: 'Osmani Getriebe-Service',
    placeId: 'xk-mitrovica',
    publicPhone: '+383 44 100 110',
    scenario: 'Getriebe-Spezialist und Mercedes-Benz-Partner in Mitrovicë.',
    selfReportedSpecializations: ['Getriebe'],
    serviceCategoryIds: ['getriebe'],
    vehicleMakeIds: ['mercedes-benz'],
    verification: 'verified',
  }),
  garage({
    id: 'demo-mitrovica-reifen',
    contactPerson: 'Besnik Haliti',
    languages: ['Shqip'],
    name: 'Mitrovica Reifen',
    placeId: 'xk-mitrovica',
    publicPhone: '+383 44 100 111',
    scenario: 'Reifen-Fachbetrieb in Mitrovicë. Montage, Auswuchten und Einlagerung.',
    selfReportedSpecializations: ['Reifen'],
    serviceCategoryIds: ['reifen'],
    vehicleMakeIds: ['opel'],
    verification: 'not_checked',
  }),
  garage({
    id: 'demo-peja-bremsen-opel',
    contactPerson: 'Arta Gashi',
    languages: ['Deutsch'],
    name: 'Asllani Werkstatt',
    placeId: 'xk-peja',
    publicPhone: '+383 44 100 112',
    scenario: 'Bremsen-Spezialist und Opel-Service in Pejë.',
    selfReportedSpecializations: ['Bremsen'],
    serviceCategoryIds: ['bremsen'],
    vehicleMakeIds: ['opel'],
    verification: 'verified',
  }),
  garage({
    id: 'demo-peja-motor-offen',
    contactPerson: 'Arben Krasniqi',
    languages: ['Shqip'],
    name: 'Peja Motor-Centrum',
    placeId: 'xk-peja',
    publicPhone: '+383 44 100 113',
    scenario: 'Motorinstandhaltung und allgemeiner Fahrzeugservice in Pejë.',
    selfReportedSpecializations: ['Motor'],
    serviceCategoryIds: ['motor'],
    vehicleMakeIds: [],
    verification: 'verified',
  }),
  garage({
    id: 'demo-prishtina-service-renault',
    contactPerson: 'Besnik Haliti',
    languages: ['Deutsch', 'Shqip'],
    name: 'Kovaçi Auto-Service',
    placeId: 'xk-pristina',
    publicPhone: '+383 44 100 114',
    scenario: 'Renault-Partner und Inspektion für alle Marken in Prishtina.',
    selfReportedSpecializations: ['Inspektion'],
    serviceCategoryIds: ['service-inspektion'],
    vehicleMakeIds: ['renault'],
    verification: 'verified',
  }),
  garage({
    id: 'demo-prishtina-elektronik-vw',
    contactPerson: 'Arta Gashi',
    languages: ['Deutsch'],
    name: 'AutoTechnik Prishtina',
    placeId: 'xk-pristina',
    publicPhone: '+383 44 100 115',
    scenario: 'Fahrzeugelektronik und VW-Diagnose im Zentrum von Prishtina.',
    selfReportedSpecializations: ['Diagnose'],
    serviceCategoryIds: ['elektronik-diagnose'],
    vehicleMakeIds: ['volkswagen'],
    verification: 'not_checked',
  }),
  garage({
    id: 'demo-prishtina-karosserie',
    contactPerson: 'Arben Krasniqi',
    languages: ['Shqip'],
    name: 'Haliti Karosserie',
    placeId: 'xk-pristina',
    publicPhone: '+383 44 100 116',
    scenario: 'Karosserie, Unfallinstandsetzung und Lackierung in Prishtina.',
    selfReportedSpecializations: ['Karosserie'],
    serviceCategoryIds: ['karosserie'],
    vehicleMakeIds: [],
    verification: 'verified',
  }),
  garage({
    id: 'demo-prizren-klima-toyota',
    contactPerson: 'Besnik Haliti',
    languages: ['Deutsch', 'Shqip'],
    name: 'Toyota-Service Prizren',
    placeId: 'xk-prizren',
    publicPhone: '+383 44 100 117',
    scenario: 'Klimaanlagen-Wartung und Toyota-Fachbetrieb in Prizren.',
    selfReportedSpecializations: ['Klimaanlage'],
    serviceCategoryIds: ['klima'],
    vehicleMakeIds: ['toyota'],
    verification: 'verified',
  }),
  garage({
    id: 'demo-prizren-getriebe-offen',
    contactPerson: 'Arta Gashi',
    languages: ['Shqip'],
    name: 'Prizren Getriebe',
    placeId: 'xk-prizren',
    publicPhone: '+383 44 100 118',
    scenario: 'Getriebe-Instandsetzung für alle Marken in Prizren.',
    selfReportedSpecializations: ['Getriebe'],
    serviceCategoryIds: ['getriebe'],
    vehicleMakeIds: [],
    verification: 'not_checked',
  }),
  garage({
    id: 'demo-ferizaj-reifen',
    contactPerson: 'Arben Krasniqi',
    languages: ['Deutsch'],
    name: 'Ferizaj Reifen-Centrum',
    placeId: 'xk-ferizaj',
    publicPhone: '+383 44 100 119',
    scenario: 'Reifen, Felgen und Auswuchten in Ferizaj. Alle Fahrzeugmarken.',
    selfReportedSpecializations: ['Reifen'],
    serviceCategoryIds: ['reifen'],
    vehicleMakeIds: ['skoda'],
    verification: 'verified',
  }),
  garage({
    id: 'demo-ferizaj-elektronik-skoda',
    contactPerson: 'Besnik Haliti',
    languages: ['Shqip'],
    name: 'Škoda-Partner Ferizaj',
    placeId: 'xk-ferizaj',
    publicPhone: '+383 44 100 120',
    scenario: 'Škoda-Spezialist und allgemeine Fahrzeugelektronik in Ferizaj.',
    selfReportedSpecializations: ['Diagnose'],
    serviceCategoryIds: ['elektronik-diagnose'],
    vehicleMakeIds: ['skoda'],
    verification: 'verified',
  }),
  garage({
    id: 'demo-gjakova-service',
    contactPerson: 'Arta Gashi',
    languages: ['Deutsch'],
    name: 'Auto-Service Gjakova',
    placeId: 'xk-gjakova',
    publicPhone: '+383 44 100 121',
    scenario: 'Vollservice und Inspektionen für alle Fahrzeuge in Gjakovë.',
    selfReportedSpecializations: ['Inspektion'],
    serviceCategoryIds: ['service-inspektion'],
    vehicleMakeIds: ['audi'],
    verification: 'not_checked',
  }),
  garage({
    id: 'demo-gjilan-klima',
    contactPerson: 'Arben Krasniqi',
    languages: ['Deutsch', 'Shqip'],
    name: 'Klima-Center Gjilan',
    placeId: 'xk-gjilan',
    publicPhone: '+383 44 100 122',
    scenario: 'Klimaanlage-Wartung, Befüllung und Reparatur in Gjilan.',
    selfReportedSpecializations: ['Klimaanlage'],
    serviceCategoryIds: ['klima'],
    vehicleMakeIds: [],
    verification: 'verified',
  }),
  garage({
    id: 'demo-mitrovica-motor-bmw',
    contactPerson: 'Besnik Haliti',
    languages: ['Shqip'],
    name: 'BMW-Service Mitrovicë',
    placeId: 'xk-mitrovica',
    publicPhone: '+383 44 100 123',
    scenario: 'BMW-Spezialist und Motorinstandhaltung in Mitrovicë.',
    selfReportedSpecializations: ['Motor'],
    serviceCategoryIds: ['motor'],
    vehicleMakeIds: ['bmw'],
    verification: 'verified',
  }),
  garage({
    id: 'demo-peja-karosserie',
    contactPerson: 'Arta Gashi',
    languages: ['Deutsch'],
    name: 'Karosserie Peja',
    placeId: 'xk-peja',
    publicPhone: '+383 44 100 124',
    scenario: 'Karosserie und Unfallreparaturen in Pejë. Schnelle Abwicklung.',
    selfReportedSpecializations: ['Karosserie'],
    serviceCategoryIds: ['karosserie'],
    vehicleMakeIds: [],
    verification: 'not_checked',
  }),
  garage({
    id: 'demo-prishtina-bremsen-offen',
    contactPerson: 'Arben Krasniqi',
    languages: ['Deutsch'],
    name: 'Bremsen-Centrum Nord',
    placeId: 'xk-pristina',
    publicPhone: '+383 44 100 125',
    scenario: 'Bremsen-Spezialist im Norden von Prishtina. Alle Fahrzeugmarken.',
    selfReportedSpecializations: ['Bremsen'],
    serviceCategoryIds: ['bremsen'],
    vehicleMakeIds: [],
    verification: 'verified',
  }),
];

/** Fictional garage operators — seeded as owners of the demo garages. */
export const demoBetreiberUsers = ['demo-betreiber-a', 'demo-betreiber-b', 'demo-betreiber-c'];

export const demoWorkflowUsers = [
  'demo-workflow-moderator',
  'demo-workflow-reviewer-a',
  'demo-workflow-reviewer-b',
  'demo-workflow-reviewer-c',
  'demo-workflow-requester-a',
  'demo-workflow-requester-b',
  'demo-workflow-requester-c',
];

/** Realistic-looking but fictional display names for demo accounts.
 *  All names are invented; verified_roles reflects each account's role in the demo scenarios. */
export const demoUserDisplayNames = {
  'demo-betreiber-a': { name: 'Arben Krasniqi', roles: [] },
  'demo-betreiber-b': { name: 'Besnik Haliti', roles: [] },
  'demo-betreiber-c': { name: 'Arta Gashi', roles: [] },
  'demo-workflow-moderator': { name: 'Mentor Lleshi', roles: ['moderator'] },
  'demo-workflow-reviewer-a': { name: 'Fjolla Berisha', roles: [] },
  'demo-workflow-reviewer-b': { name: 'Visar Morina', roles: [] },
  'demo-workflow-reviewer-c': { name: 'Albana Bytyqi', roles: [] },
  'demo-workflow-requester-a': { name: 'Liridon Hoti', roles: [] },
  'demo-workflow-requester-b': { name: 'Erjona Asllani', roles: [] },
  'demo-workflow-requester-c': { name: 'Shpend Gashi', roles: [] },
};

export const demoWorkflowReviews = [
  {
    authorUserId: 'demo-workflow-reviewer-a',
    communication: 4,
    evidenceKind: 'other_service_proof',
    id: 'demo-review-prishtina-bremsen-a',
    priceTransparency: 4,
    punctuality: 4,
    serviceCategoryId: 'bremsen',
    text: 'Schnelle und saubere Arbeit. Bremsbeläge vorne und hinten gewechselt, alles gut erklärt. Preis war fair.',
    vehicleMakeId: 'skoda',
    visitMonth: '2026-04-01',
    workQuality: 4,
    garageId: 'demo-prishtina-bremsen',
  },
  {
    authorUserId: 'demo-workflow-reviewer-b',
    communication: 3,
    evidenceKind: 'other_service_proof',
    id: 'demo-review-prishtina-bremsen-b',
    priceTransparency: 3,
    punctuality: 4,
    serviceCategoryId: 'bremsen',
    text: 'Arbeit wurde ordentlich erledigt, aber die Wartezeit war länger als angekündigt. Kommunikation könnte besser sein.',
    vehicleMakeId: 'skoda',
    visitMonth: '2026-05-01',
    workQuality: 4,
    garageId: 'demo-prishtina-bremsen',
  },
  {
    authorUserId: 'demo-workflow-reviewer-c',
    communication: 2,
    evidenceKind: 'other_service_proof',
    id: 'demo-review-ferizaj-bremsen-a',
    priceTransparency: 2,
    punctuality: 3,
    serviceCategoryId: 'bremsen',
    text: 'Leider nicht zufrieden. Bremsen immer noch nicht in Ordnung nach dem Besuch, musste nochmals wiederkommen.',
    vehicleMakeId: undefined,
    visitMonth: '2026-03-01',
    workQuality: 2,
    garageId: 'demo-ferizaj-bremsen-offen',
  },
  {
    authorUserId: 'demo-workflow-reviewer-a',
    communication: 3,
    evidenceKind: 'other_service_proof',
    id: 'demo-review-ferizaj-bremsen-b',
    priceTransparency: 3,
    punctuality: 3,
    serviceCategoryId: 'bremsen',
    text: 'Durchschnittliche Erfahrung. Arbeit wurde gemacht, aber nichts Besonderes. Preis in Ordnung.',
    vehicleMakeId: undefined,
    visitMonth: '2026-06-01',
    workQuality: 3,
    garageId: 'demo-ferizaj-bremsen-offen',
  },
  {
    authorUserId: 'demo-workflow-reviewer-b',
    communication: 5,
    evidenceKind: 'other_service_proof',
    id: 'demo-review-prishtina-reifen-a',
    priceTransparency: 5,
    punctuality: 4,
    serviceCategoryId: 'reifen',
    text: 'Sehr empfehlenswert! Reifenwechsel in unter 30 Minuten, freundliches Personal und guter Preis.',
    vehicleMakeId: 'toyota',
    visitMonth: '2026-05-01',
    workQuality: 5,
    garageId: 'demo-prishtina-reifen',
  },
  {
    authorUserId: 'demo-workflow-reviewer-c',
    communication: 4,
    evidenceKind: 'other_service_proof',
    id: 'demo-review-prishtina-reifen-b',
    priceTransparency: 4,
    punctuality: 5,
    serviceCategoryId: 'reifen',
    text: 'Zuverlässiger Service. Termine werden eingehalten und die Arbeit ist solide. Gerne wieder.',
    vehicleMakeId: 'toyota',
    visitMonth: '2026-06-01',
    workQuality: 4,
    garageId: 'demo-prishtina-reifen',
  },
];

export const demoWorkflowRequests = [
  {
    id: 'demo-request-prishtina-bremsen',
    earliestDropoffOn: '2026-10-02',
    latestPickupOn: '2026-10-06',
    ownerUserId: 'demo-workflow-requester-a',
    searchAreas: [{ id: 'demo-request-area-prishtina', placeId: 'xk-pristina', radiusM: 20000 }],
    serviceCategoryId: 'bremsen',
    symptom:
      'Bremspedal fühlt sich weich an und das Fahrzeug zieht beim Bremsen leicht nach links. Bitte Bremsen prüfen.',
  },
  {
    id: 'demo-request-prizren-klima',
    earliestDropoffOn: '2026-10-08',
    latestPickupOn: '2026-10-12',
    ownerUserId: 'demo-workflow-requester-b',
    searchAreas: [{ id: 'demo-request-area-prizren', placeId: 'xk-prizren', radiusM: 30000 }],
    serviceCategoryId: 'klima',
    symptom:
      'Klimaanlage kühlt nicht mehr richtig, Kompressor macht ein komisches Geräusch. Bitte prüfen und Kosten schätzen.',
  },
  {
    id: 'demo-request-ferizaj-service',
    earliestDropoffOn: '2026-10-15',
    latestPickupOn: '2026-10-18',
    ownerUserId: 'demo-workflow-requester-c',
    searchAreas: [{ id: 'demo-request-area-ferizaj', placeId: 'xk-ferizaj', radiusM: 25000 }],
    serviceCategoryId: 'service-inspektion',
    symptom:
      'Jahresinspektion fällig, ausserdem Ölwechsel und Reifencheck. Bitte Termin vorschlagen.',
  },
];
