const baseDescription = 'Ausschliesslich fiktive lokale Entwicklungsdaten.';

function workshop(input) {
  return {
    contactPerson: `Lokale Demo-Person ${input.id}`,
    description: `${baseDescription} ${input.scenario}`,
    ...input,
  };
}

export const demoWorkshops = [
  workshop({
    id: 'demo-prishtina-bremsen',
    languages: ['Deutsch', 'Shqip'],
    name: 'DEMO · Bremsen Prishtina',
    placeId: 'xk-pristina',
    publicPhone: '+99900000001',
    scenario: 'Kein echter Betrieb und kein echtes Angebot.',
    selfReportedSpecializations: ['Bremsen'],
    serviceCategoryIds: ['bremsen'],
    vehicleMakeIds: ['skoda'],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-prishtina-reifen',
    languages: ['Shqip'],
    name: 'DEMO · Reifen Prishtina',
    placeId: 'xk-pristina',
    publicPhone: '+99900000002',
    scenario: 'Dieses Profil zeigt einen markenoffenen Betrieb ohne Unternehmenskennzeichen.',
    selfReportedSpecializations: ['Reifenwechsel'],
    serviceCategoryIds: ['reifen'],
    vehicleMakeIds: [],
    verification: 'not_checked',
  }),
  workshop({
    id: 'demo-ferizaj-bremsen-offen',
    languages: ['Deutsch'],
    name: 'DEMO · Bremsen Ferizaj',
    placeId: 'xk-ferizaj',
    publicPhone: '+99900000003',
    scenario: 'Dieses Profil ist für Mehrortsuche und Markenoffenheit bestimmt.',
    selfReportedSpecializations: ['Bremsen', 'Inspektion'],
    serviceCategoryIds: ['bremsen', 'service-inspektion'],
    vehicleMakeIds: [],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-prizren-bremsen-vw',
    languages: ['Deutsch', 'Shqip'],
    name: 'DEMO · Bremsen Prizren',
    placeId: 'xk-prizren',
    publicPhone: '+99900000004',
    scenario: 'Dieses Profil ist ein Markenfilter-Gegenbeispiel.',
    selfReportedSpecializations: ['Bremsen'],
    serviceCategoryIds: ['bremsen'],
    vehicleMakeIds: ['volkswagen'],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-peja-klima',
    languages: ['Shqip'],
    name: 'DEMO · Klima Pejë',
    placeId: 'xk-peja',
    publicPhone: '+99900000005',
    scenario: 'Dieses Profil deckt Leistung und Sprachfilter ausserhalb von Prishtina ab.',
    selfReportedSpecializations: ['Klimaanlage'],
    serviceCategoryIds: ['klima'],
    vehicleMakeIds: ['toyota'],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-gjakova-motor-audi',
    languages: ['Deutsch'],
    name: 'DEMO · Motor Gjakovë',
    placeId: 'xk-gjakova',
    publicPhone: '+99900000006',
    scenario: 'Dieses Profil prüft Motor- und Markenfilter.',
    selfReportedSpecializations: ['Motor'],
    serviceCategoryIds: ['motor'],
    vehicleMakeIds: ['audi'],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-gjakova-karosserie',
    languages: ['Shqip'],
    name: 'DEMO · Karosserie Gjakovë',
    placeId: 'xk-gjakova',
    publicPhone: '+99900000007',
    scenario: 'Dieses Profil zeigt einen ungeprüften Karosseriebetrieb.',
    selfReportedSpecializations: ['Karosserie'],
    serviceCategoryIds: ['karosserie'],
    vehicleMakeIds: [],
    verification: 'not_checked',
  }),
  workshop({
    id: 'demo-gjilan-elektronik-bmw',
    languages: ['Deutsch', 'Shqip'],
    name: 'DEMO · Elektronik Gjilan',
    placeId: 'xk-gjilan',
    publicPhone: '+99900000008',
    scenario: 'Dieses Profil prüft Elektronik und eine eingeschränkte Fahrzeugmarke.',
    selfReportedSpecializations: ['Diagnose'],
    serviceCategoryIds: ['elektronik-diagnose'],
    vehicleMakeIds: ['bmw'],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-gjilan-service-offen',
    languages: ['Shqip'],
    name: 'DEMO · Service Gjilan',
    placeId: 'xk-gjilan',
    publicPhone: '+99900000009',
    scenario: 'Dieses Profil prüft markenoffenen Service.',
    selfReportedSpecializations: ['Inspektion'],
    serviceCategoryIds: ['service-inspektion'],
    vehicleMakeIds: [],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-mitrovica-getriebe-mercedes',
    languages: ['Deutsch'],
    name: 'DEMO · Getriebe Mitrovicë',
    placeId: 'xk-mitrovica',
    publicPhone: '+99900000010',
    scenario: 'Dieses Profil prüft Getriebe und Mercedes-Benz.',
    selfReportedSpecializations: ['Getriebe'],
    serviceCategoryIds: ['getriebe'],
    vehicleMakeIds: ['mercedes-benz'],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-mitrovica-reifen',
    languages: ['Shqip'],
    name: 'DEMO · Reifen Mitrovicë',
    placeId: 'xk-mitrovica',
    publicPhone: '+99900000011',
    scenario: 'Dieses Profil prüft einen weiteren Reifen-Leerfall.',
    selfReportedSpecializations: ['Reifen'],
    serviceCategoryIds: ['reifen'],
    vehicleMakeIds: ['opel'],
    verification: 'not_checked',
  }),
  workshop({
    id: 'demo-peja-bremsen-opel',
    languages: ['Deutsch'],
    name: 'DEMO · Bremsen Pejë',
    placeId: 'xk-peja',
    publicPhone: '+99900000012',
    scenario: 'Dieses Profil prüft Bremsen ausserhalb des ersten Suchorts.',
    selfReportedSpecializations: ['Bremsen'],
    serviceCategoryIds: ['bremsen'],
    vehicleMakeIds: ['opel'],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-peja-motor-offen',
    languages: ['Shqip'],
    name: 'DEMO · Motor Pejë',
    placeId: 'xk-peja',
    publicPhone: '+99900000013',
    scenario: 'Dieses Profil prüft markenoffenen Motorservice.',
    selfReportedSpecializations: ['Motor'],
    serviceCategoryIds: ['motor'],
    vehicleMakeIds: [],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-prishtina-service-renault',
    languages: ['Deutsch', 'Shqip'],
    name: 'DEMO · Service Prishtina',
    placeId: 'xk-pristina',
    publicPhone: '+99900000014',
    scenario: 'Dieses Profil prüft Service und Renault.',
    selfReportedSpecializations: ['Inspektion'],
    serviceCategoryIds: ['service-inspektion'],
    vehicleMakeIds: ['renault'],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-prishtina-elektronik-vw',
    languages: ['Deutsch'],
    name: 'DEMO · Elektronik Prishtina',
    placeId: 'xk-pristina',
    publicPhone: '+99900000015',
    scenario: 'Dieses Profil prüft Diagnose und Volkswagen.',
    selfReportedSpecializations: ['Diagnose'],
    serviceCategoryIds: ['elektronik-diagnose'],
    vehicleMakeIds: ['volkswagen'],
    verification: 'not_checked',
  }),
  workshop({
    id: 'demo-prishtina-karosserie',
    languages: ['Shqip'],
    name: 'DEMO · Karosserie Prishtina',
    placeId: 'xk-pristina',
    publicPhone: '+99900000016',
    scenario: 'Dieses Profil prüft einen zusätzlichen Leistungsvergleich.',
    selfReportedSpecializations: ['Karosserie'],
    serviceCategoryIds: ['karosserie'],
    vehicleMakeIds: [],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-prizren-klima-toyota',
    languages: ['Deutsch', 'Shqip'],
    name: 'DEMO · Klima Prizren',
    placeId: 'xk-prizren',
    publicPhone: '+99900000017',
    scenario: 'Dieses Profil prüft Klima und Toyota.',
    selfReportedSpecializations: ['Klimaanlage'],
    serviceCategoryIds: ['klima'],
    vehicleMakeIds: ['toyota'],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-prizren-getriebe-offen',
    languages: ['Shqip'],
    name: 'DEMO · Getriebe Prizren',
    placeId: 'xk-prizren',
    publicPhone: '+99900000018',
    scenario: 'Dieses Profil prüft markenoffenes Getriebe.',
    selfReportedSpecializations: ['Getriebe'],
    serviceCategoryIds: ['getriebe'],
    vehicleMakeIds: [],
    verification: 'not_checked',
  }),
  workshop({
    id: 'demo-ferizaj-reifen',
    languages: ['Deutsch'],
    name: 'DEMO · Reifen Ferizaj',
    placeId: 'xk-ferizaj',
    publicPhone: '+99900000019',
    scenario: 'Dieses Profil prüft einen weiteren Reifenfilter.',
    selfReportedSpecializations: ['Reifen'],
    serviceCategoryIds: ['reifen'],
    vehicleMakeIds: ['skoda'],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-ferizaj-elektronik-skoda',
    languages: ['Shqip'],
    name: 'DEMO · Elektronik Ferizaj',
    placeId: 'xk-ferizaj',
    publicPhone: '+99900000020',
    scenario: 'Dieses Profil prüft Diagnose und Škoda.',
    selfReportedSpecializations: ['Diagnose'],
    serviceCategoryIds: ['elektronik-diagnose'],
    vehicleMakeIds: ['skoda'],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-gjakova-service',
    languages: ['Deutsch'],
    name: 'DEMO · Service Gjakovë',
    placeId: 'xk-gjakova',
    publicPhone: '+99900000021',
    scenario: 'Dieses Profil prüft einen Service-Leerfall.',
    selfReportedSpecializations: ['Inspektion'],
    serviceCategoryIds: ['service-inspektion'],
    vehicleMakeIds: ['audi'],
    verification: 'not_checked',
  }),
  workshop({
    id: 'demo-gjilan-klima',
    languages: ['Deutsch', 'Shqip'],
    name: 'DEMO · Klima Gjilan',
    placeId: 'xk-gjilan',
    publicPhone: '+99900000022',
    scenario: 'Dieses Profil prüft einen weiteren Klima-Filter.',
    selfReportedSpecializations: ['Klimaanlage'],
    serviceCategoryIds: ['klima'],
    vehicleMakeIds: [],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-mitrovica-motor-bmw',
    languages: ['Shqip'],
    name: 'DEMO · Motor Mitrovicë',
    placeId: 'xk-mitrovica',
    publicPhone: '+99900000023',
    scenario: 'Dieses Profil prüft Motor und BMW.',
    selfReportedSpecializations: ['Motor'],
    serviceCategoryIds: ['motor'],
    vehicleMakeIds: ['bmw'],
    verification: 'verified',
  }),
  workshop({
    id: 'demo-peja-karosserie',
    languages: ['Deutsch'],
    name: 'DEMO · Karosserie Pejë',
    placeId: 'xk-peja',
    publicPhone: '+99900000024',
    scenario: 'Dieses Profil prüft Karosserie und Markenoffenheit.',
    selfReportedSpecializations: ['Karosserie'],
    serviceCategoryIds: ['karosserie'],
    vehicleMakeIds: [],
    verification: 'not_checked',
  }),
  workshop({
    id: 'demo-prishtina-bremsen-offen',
    languages: ['Deutsch'],
    name: 'DEMO · Bremsen Nord Prishtina',
    placeId: 'xk-pristina',
    publicPhone: '+99900000025',
    scenario: 'Dieses Profil prüft einen markenoffenen Ranking-Gleichstand.',
    selfReportedSpecializations: ['Bremsen'],
    serviceCategoryIds: ['bremsen'],
    vehicleMakeIds: [],
    verification: 'verified',
  }),
];

export const demoWorkflowUsers = [
  'demo-workflow-moderator',
  'demo-workflow-reviewer-a',
  'demo-workflow-reviewer-b',
  'demo-workflow-reviewer-c',
  'demo-workflow-requester-a',
  'demo-workflow-requester-b',
  'demo-workflow-requester-c',
];

export const demoWorkflowReviews = [
  {
    authorUserId: 'demo-workflow-reviewer-a',
    communication: 4,
    evidenceKind: 'other_service_proof',
    id: 'demo-review-prishtina-bremsen-a',
    priceTransparency: 4,
    punctuality: 4,
    serviceCategoryId: 'bremsen',
    text: 'Lokale Demo-Bewertung: Fiktiver Datensatz für die Entwicklungsansicht, keine Erfahrung mit einem realen Betrieb.',
    vehicleMakeId: 'skoda',
    visitMonth: '2026-04-01',
    workQuality: 4,
    workshopId: 'demo-prishtina-bremsen',
  },
  {
    authorUserId: 'demo-workflow-reviewer-b',
    communication: 3,
    evidenceKind: 'other_service_proof',
    id: 'demo-review-prishtina-bremsen-b',
    priceTransparency: 3,
    punctuality: 4,
    serviceCategoryId: 'bremsen',
    text: 'Lokale Demo-Bewertung: Ausschliesslich fiktiver Testfall für eine zweite belegte Entwicklungsbewertung.',
    vehicleMakeId: 'skoda',
    visitMonth: '2026-05-01',
    workQuality: 4,
    workshopId: 'demo-prishtina-bremsen',
  },
  {
    authorUserId: 'demo-workflow-reviewer-c',
    communication: 2,
    evidenceKind: 'other_service_proof',
    id: 'demo-review-ferizaj-bremsen-a',
    priceTransparency: 2,
    punctuality: 3,
    serviceCategoryId: 'bremsen',
    text: 'Lokale Demo-Bewertung: Fiktiver negativer Testfall ohne Bezug zu einer echten Werkstatt oder Reparatur.',
    vehicleMakeId: undefined,
    visitMonth: '2026-03-01',
    workQuality: 2,
    workshopId: 'demo-ferizaj-bremsen-offen',
  },
  {
    authorUserId: 'demo-workflow-reviewer-a',
    communication: 3,
    evidenceKind: 'other_service_proof',
    id: 'demo-review-ferizaj-bremsen-b',
    priceTransparency: 3,
    punctuality: 3,
    serviceCategoryId: 'bremsen',
    text: 'Lokale Demo-Bewertung: Fiktiver Entwicklungsdatensatz mit einer bewusst durchschnittlichen Bewertung.',
    vehicleMakeId: undefined,
    visitMonth: '2026-06-01',
    workQuality: 3,
    workshopId: 'demo-ferizaj-bremsen-offen',
  },
  {
    authorUserId: 'demo-workflow-reviewer-b',
    communication: 5,
    evidenceKind: 'other_service_proof',
    id: 'demo-review-prishtina-reifen-a',
    priceTransparency: 5,
    punctuality: 4,
    serviceCategoryId: 'reifen',
    text: 'Lokale Demo-Bewertung: Fiktiver Reifen-Testfall für die lokale Profilansicht, kein echtes Testimonial.',
    vehicleMakeId: 'toyota',
    visitMonth: '2026-05-01',
    workQuality: 5,
    workshopId: 'demo-prishtina-reifen',
  },
  {
    authorUserId: 'demo-workflow-reviewer-c',
    communication: 4,
    evidenceKind: 'other_service_proof',
    id: 'demo-review-prishtina-reifen-b',
    priceTransparency: 4,
    punctuality: 5,
    serviceCategoryId: 'reifen',
    text: 'Lokale Demo-Bewertung: Zweiter fiktiver Entwicklungsfall ohne reale Person, Rechnung oder Besuch.',
    vehicleMakeId: 'toyota',
    visitMonth: '2026-06-01',
    workQuality: 4,
    workshopId: 'demo-prishtina-reifen',
  },
];

export const demoWorkflowRequests = [
  {
    id: 'demo-request-prishtina-bremsen',
    ownerUserId: 'demo-workflow-requester-a',
    searchAreas: [{ id: 'demo-request-area-prishtina', placeId: 'xk-pristina', radiusM: 20000 }],
    serviceCategoryId: 'bremsen',
    symptom: 'Fiktive lokale Anfrage: Bremsen prüfen.',
  },
  {
    id: 'demo-request-prizren-klima',
    ownerUserId: 'demo-workflow-requester-b',
    searchAreas: [{ id: 'demo-request-area-prizren', placeId: 'xk-prizren', radiusM: 30000 }],
    serviceCategoryId: 'klima',
    symptom: 'Fiktive lokale Anfrage: Klimaanlage prüfen.',
  },
  {
    id: 'demo-request-ferizaj-service',
    ownerUserId: 'demo-workflow-requester-c',
    searchAreas: [{ id: 'demo-request-area-ferizaj', placeId: 'xk-ferizaj', radiusM: 25000 }],
    serviceCategoryId: 'service-inspektion',
    symptom: 'Fiktive lokale Anfrage: Service und Inspektion.',
  },
];
